### ISSUE TITLE
[EN] exception occurred while executing a query

### ISSUE THREAD

**Issue by ruandrade** [baimard/gestion#118]
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_gestion_client' doesn't exist

**Comment by baimard** [comment]
Welcome, I need more information

Your :
- database version
- nextcloud version

When that happend ?

And all relevant informations

**Comment by glOOmyART** [comment]
i have the same problem

Nextcloud Hub II (23.0.0) (after updating to 23.0.1 it still persists)
MariaDB 10.5.13

the app is eventually downloaded but can't be activated

**Comment by baimard** [comment]
This is an update or an installation ?

**Comment by glOOmyART** [comment]
sorry, it's an installation

i tried installing the app in 23.0.0 with this error, then noticed i needed to update NC so i did that
then i went back to the apps section an noticed the app was actually downloaded but can't be activated
so i tried the full process again by deleting the app and then reinstalling it but the error persisted...
app is downloaded but can't be activated

**Comment by baimard** [comment]
Have you change the prefix of nextcloud installation ?

**Comment by baimard** [comment]
Problème identifié, I will try to fix quickly

**Comment by caasi-dev** [comment]
Same here,

**Maria DB**
mariadb  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

** Nextcloud**
Nextcloud Hub II (23.0.1)

**Comment by cloo** [comment]
In my case error occurs when trying to install: 

![220131-140915](https://user-images.githubusercontent.com/651760/151792238-da8b0aa8-28fb-45ac-aecd-ef70dbee856d.png)

Tech data: 

nextcloud version 21.0.4
server Ubuntu 18.04
PHP version 7.4.13
MySQL version 10.5.8

**Comment by baimard** [comment]
New version with an hotfix will be available in next hour.

I'm so sorry for that !

**Comment by caasi-dev** [comment]
> New version with an hotfix will be available in next hour.
> 
> I'm so sorry for that !

Looking forward to it, thanks for quick turn around!!

**Comment by baimard** [comment]
https://github.com/baimard/gestion/actions/runs/1772555558

**Comment by caasi-dev** [comment]
> New version with an hotfix will be available in next hour.
> 
> I'm so sorry for that !

Can confirm that version [https://github.com/baimard/gestion/releases/tag/2.0.1](Version 2.0.1) fixes the issue for me!

Thank you!!

**Comment by baimard** [comment]
Wow it's a very good news ! I just won experience for future release !
