### ISSUE TITLE
How to open an issue?

### ISSUE THREAD

**Issue by baimard** [baimard/gestion#119]
To open an issue please : 

- Be cool ...
- give your nextcloud version
- give your database version
- give your php version

Tell me how that happened, I really like short stories with one or two sentences.

Also tell me, If the bug is critical, I would do the best to help you quickly. (Except, Friday night, Saturday, sunday, because I have a life IRL)

**Comment by Moini** [comment]
Did you know you can use issue templates for that? I didn't see this.

**Comment by baimard** [comment]
I have just added template this day !

**Comment by Moini** [comment]
Merci!
