### ISSUE TITLE
[FR]Modification informations entreprise

### ISSUE THREAD

**Issue by zagub59** [baimard/gestion#12]
Bonjour Benjamin,

Tout d'abord, bravo pour le travail accompli ! 

J'ouvre cet issue car j'ai beau chercher, je ne trouve pas où modifier les informations de mon entreprise une fois la saisie initiale effectuée. 

De quelle manière puis-je m'y prendre ?

Merci !

**Comment by baimard** [comment]
Bonjour !

Merci pour les encouragements et ton retour !

En bas à gauche dans les paramètres, tu y trouveras également le répertoire où s'enregistrent les devis et les factures.

Tu as des vidéos explicatives ici : https://baimard.github.io/gestion

**Comment by baimard** [comment]
c'est bon pour vous ?

**Comment by zagub59** [comment]
Hello @baimard,
Désolé de ne pas avoir répondu ! J'ai eu des soucis de base de données sur mon instance Nextcloud qui ont mis en standby l'usage de l'application. 
C'est désormais OK, je vais tester son usage en environnement réel. Merci pour ton travail !

**Comment by baimard** [comment]
Salut pas de soucis hésite pas :)
