### ISSUE TITLE
SQL exception during install

### ISSUE THREAD

**Issue by hj-beckers** [baimard/gestion#120]
During download and installation the following error occurs:

"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'oc.oc_gestion_client' doesn't exist"

nextcloud version 22.2.3
server Ubuntu 20.04.3 LTS (Raspberry pi)
PHP version 7.4.3
MariaDB version 10.3.32

**Comment by cloo** [comment]
I get the same error. 

nextcloud version 21.0.4
server Ubuntu 18.04 
PHP version 7.4.13
MySQL version 10.5.8

**Comment by baimard** [comment]
https://github.com/baimard/gestion/issues/118

**Comment by baimard** [comment]
New version with an hotfix will be available in next hour.

I'm so sorry for that !
