### ISSUE TITLE
Cannot start the app: Internal server error right after install

### ISSUE THREAD

**Issue by cloo** [baimard/gestion#121]
When clicking app icon after installing, internal server error is displayed:

 
![220131-140106](https://user-images.githubusercontent.com/651760/151790979-929304bf-9372-4ec8-b954-2a1db2fc2ad2.png)

Reinstalling does not help. 

Nextcloud 22.2.3
via Yunohost

**Comment by baimard** [comment]
https://github.com/baimard/gestion/issues/118

**Comment by baimard** [comment]
New version with an hotfix will be available in next hour.

I'm so sorry for that !
