### ISSUE TITLE
[EN] Unable to create new clients/invoices/products

### ISSUE THREAD

**Issue by baimard** [baimard/gestion#135]
### Discussed in https://github.com/baimard/gestion/discussions/134

<div type='discussions-op-text'>

<sup>Originally posted by **ironiemix** February  3, 2022</sup>
Hi there, 

thanks a lot for your work on this plugin. I try to use it, but I ran into a dead end and am suspecting that I am missing something crucial.

I entered the information for my "enterprise", that worked o.k., but when I go to the customers entry,  the table says 'No data available in table" and I am unable to create a customer, when I click on "Add customer" nothing happens. 

The same happens in the other sections, the tables all say 'No data available in table" and I am unable to add any entrys.

In addition, when I open the invoice or product page I get an error saying

```
405 Method Not Allowed

Method Not Allowed
The requested method PROPFIND is not allowed for this URL
```

What am I missing here? Any help would be greatly appreciated, TIA, 

Frank

- Nexcloud Hub 23.0.0
- Gestion 2.0.1</div>

**Comment by ironiemix** [comment]
Hello Benjamin, 

I see the following tables with "gestion" in my DB: 

```
| oc_gestion_client                          |
| oc_gestion_configuration                   |
| oc_gestion_devis                           |
| oc_gestion_facture                         |
| oc_gestion_produit                         |
| oc_gestion_produit_devis                   | 
```

i.e.
```
describe oc_gestion_client ;
+--------------+-------------+------+-----+---------+----------------+
| Field        | Type        | Null | Key | Default | Extra          |
+--------------+-------------+------+-----+---------+----------------+
| id           | int(11)     | NO   | PRI | NULL    | auto_increment |
| nom          | longtext    | NO   |     | NULL    |                |
| prenom       | longtext    | NO   |     | NULL    |                |
| legal_one    | longtext    | NO   |     | NULL    |                |
| entreprise   | longtext    | NO   |     | NULL    |                |
| telephone    | longtext    | NO   |     | NULL    |                |
| mail         | longtext    | NO   |     | NULL    |                |
| adresse      | longtext    | NO   |     | NULL    |                |
| id_nextcloud | varchar(64) | NO   |     | NULL    |                |
+--------------+-------------+------+-----+---------+----------------+
9 rows in set (0.004 sec)
```

```
select * from oc_gestion_client;
Empty set (0.001 sec)
```

If it helps, I can get you access to my instance. The Server is running debian 11 with php 7.4.

**Comment by baimard** [comment]
Do tout have a reverse proxy or a WAF ?

**Comment by ironiemix** [comment]
No, this is a very small private instance (10 users), it is deployed bare metal, no docker, no reverse proxy,  just plain old LAMP. It resides behind a Port-Forwarding for Port 443, so other ports are not accessible from the outside World. But the nextcloud service is only accessible in a server-subpath (https://server.domain.tld/nextcloud/), could this be an issue?

**Comment by baimard** [comment]
Dont know I need the full request

But I know where is the probem.

**Comment by ironiemix** [comment]
Do you need some additional information from me?

**Comment by baimard** [comment]
Maybe an Access ? If you Can ?

**Comment by baimard** [comment]
I will push version 2.0. : let me know if it's ok for you. don't forget to clear your cache because of javascript script.

**Comment by ironiemix** [comment]
It works now, thanks a lot!
