### ISSUE TITLE
[EN] Unable to add my company.

### ISSUE THREAD

**Issue by posix4e** [baimard/gestion#141]
After clearing my cache and installing gestion I got
```
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "id" violates not-null constraint DETAIL: Failing row contains (null, Your company name, Your company contact surname, Your company contact name, Company legal information line one, Company legal information line two, Your company email, Your company phone, Your company address, /, All Legal mentions, disclaimer or everything you want to place i..., 0, 0, EUR, 1, posix4e).
```
![image](https://user-images.githubusercontent.com/806363/152545219-17d887b9-dfaf-4ce7-9be2-2851579e25e5.png)

**Comment by baimard** [comment]
Thank you for reporting don't forget that : https://github.com/baimard/gestion/issues/119

Are you on postgre ?

**Comment by posix4e** [comment]
Yep I used nextcloud serverless

**Comment by baimard** [comment]
In the file gestion/lib/Db/Bdd.php : 

line 172 
```
 $sql = "INSERT INTO `".$this->tableprefix."configuration` (`id`, `entreprise`, `nom`, `prenom`, `legal_one`, `legal_two`, `mail`, `telephone`, `adresse`, `path`, `id_nextcloud`,`mentions_default`,`tva_default`,`devise`) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?, '/', ?, ?, '0',?);"; 
```

Replace by : 

```
 $sql = "INSERT INTO `".$this->tableprefix."configuration` (`entreprise`, `nom`, `prenom`, `legal_one`, `legal_two`, `mail`, `telephone`, `adresse`, `path`, `id_nextcloud`,`mentions_default`,`tva_default`,`devise`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, '/', ?, ?, '0',?);";
```

Tell if that work for you please :)

**Comment by baimard** [comment]
Any news ?

**Comment by sirautj** [comment]
> In the file gestion/lib/Db/Bdd.php :
> 
> line 172
> 
> ```
>  $sql = "INSERT INTO `".$this->tableprefix."configuration` (`id`, `entreprise`, `nom`, `prenom`, `legal_one`, `legal_two`, `mail`, `telephone`, `adresse`, `path`, `id_nextcloud`,`mentions_default`,`tva_default`,`devise`) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?, '/', ?, ?, '0',?);"; 
> ```
> 
> Replace by :
> 
> ```
>  $sql = "INSERT INTO `".$this->tableprefix."configuration` (`entreprise`, `nom`, `prenom`, `legal_one`, `legal_two`, `mail`, `telephone`, `adresse`, `path`, `id_nextcloud`,`mentions_default`,`tva_default`,`devise`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, '/', ?, ?, '0',?);";
> ```
> 
> Tell me, if that work for you please :)

That solved the issue for me
Thank you!

**Comment by baimard** [comment]
2.0.4 in next days ... sorry for the delay
