### ISSUE TITLE
[EN] Welcome page flashes on screen when selecting customer / quote etc...

### ISSUE THREAD

**Issue by David-Else** [baimard/gestion#142]
Hi, I just downloaded this for the first time via Nextcloud Apps (v2.02), thanks for making it!

I am afraid there is a bug before I start to use it. When it started I added my company details, but now this welcome screen very quickly appears and disappears when I select any option:

![bug](https://user-images.githubusercontent.com/12832280/153028666-d0c859c7-dd41-40fa-8524-1fa3564a357c.png)

**Comment by baimard** [comment]
Dear thanks you for this issues. Juste wait few seconds. This is an identified bug :)

**Comment by baimard** [comment]
NB for me
- Set modal content in database maybe can solve the problem
