### ISSUE TITLE
[FR] erreurs de traduction

### ISSUE THREAD

**Issue by mjmdurand** [baimard/gestion#143]
Bonjour,
Il y a quelques erreurs de typo dans la version française : 
- à l'écran "devis" => "Open" à la place de "Ouvrir" 
- à l'écran "devis" => "Numéro de devis" à la place de "Nom/Prénom client"
![Screenshot_1297](https://user-images.githubusercontent.com/25443389/153560566-0a1a0c3c-8695-46e1-9b6f-1cb059201d25.png)

- sur l'écran d'édition des devis "PART" => "PAR"
- ![Screenshot_1295](https://user-images.githubusercontent.com/25443389/153559179-b5d10424-e9bd-48db-8dd2-a5a1dc584bfd.png)

- Previous/Next à la place de Précédent/Suivant en bas des tableaux

**Comment by baimard** [comment]
Merci de ta contribution, je vais faire le nécessaire :)

**Comment by baimard** [comment]
J'ai un problème avec le système de traduction général dans les tableaux... je suis entrain de chercher ce qui se passe.

Sinon pour le Part par j'ai modifié.
