### ISSUE TITLE
[EN] l10n: There are no text strings in Transifex

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#146]
**1.** The following text strings are missing from Transifex:

https://github.com/baimard/gestion/blob/dd087361513c911944d5c569239ae707712f127b/src/js/modules/ajaxRequest.mjs#L27
https://github.com/baimard/gestion/blob/dd087361513c911944d5c569239ae707712f127b/src/js/modules/ajaxRequest.mjs#L51
https://github.com/baimard/gestion/blob/dd087361513c911944d5c569239ae707712f127b/src/js/modules/ajaxRequest.mjs#L234
https://github.com/baimard/gestion/blob/dd087361513c911944d5c569239ae707712f127b/src/js/modules/ajaxRequest.mjs#L236
https://github.com/baimard/gestion/blob/be3ed14b2fb4c6a7ddeac1a2c6193773fa7a3933/src/js/modules/list.mjs#L185
https://github.com/baimard/gestion/blob/be3ed14b2fb4c6a7ddeac1a2c6193773fa7a3933/src/js/modules/list.mjs#L187

**2.** Change text strings:

`disable` -> `Disable`
`enable` -> `Enable`

**3.** All text strings from [mainFunction.mjs](https://github.com/baimard/gestion/blob/dd087361513c911944d5c569239ae707712f127b/src/js/modules/mainFunction.mjs) are also missing.

![obraz](https://user-images.githubusercontent.com/47037905/153614880-04ab75f2-6023-4218-9826-7f69491844e4.png)

![obraz](https://user-images.githubusercontent.com/47037905/153635661-b54957df-ebc4-44f6-b104-3e6ed493934e.png)

**Comment by baimard** [comment]
Thank you for repporting ! I will have a look

**Comment by baimard** [comment]
All translations from mjs module not work, maybe transifex problem ?

**Comment by Valdnet** [comment]
This seems to be a problem on the repository.
@rakekniven what do you think?

**Comment by baimard** [comment]
> AFAIK "mjs" is not a supported file extension. Where are these files from?

JavaScript Module :(

**Comment by baimard** [comment]
> 

For transifex it's a bug or features ?

**Comment by rakekniven** [comment]
Not sure if this is related with Transifex or the CI tools/scripts of Nextcloud. Let me check this but I am short in time today.

**Comment by baimard** [comment]
not a problem i'm short too. Do it when you have time :)

**Comment by baimard** [comment]
Thanks you @rakekniven

**Comment by baimard** [comment]
https://github.com/nextcloud/docker-ci/pull/362

**Comment by nickvergessen** [comment]
Works now
![Bildschirmfoto von 2022-03-10 10-50-49](https://user-images.githubusercontent.com/213943/157636407-25aacb35-40a2-4d40-b74d-cd10e0d26e4f.png)

**Comment by baimard** [comment]
@nickvergessen this is a very good news, thank you for the work and for your time.
