### ISSUE TITLE
[EN] l10n: Add currency names to Transifex

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#147]
I suggest adding [currency](https://github.com/baimard/gestion/blob/57005a5ebe6b32377adc53208276152acb98b379/src/js/modules/currency.mjs) names to Transifex so that they appear translated for the user.

![obraz](https://user-images.githubusercontent.com/47037905/153610526-f28a1e8c-056d-4b39-a833-ceaa3f2d31e3.png)

**Comment by baimard** [comment]
I don't know how to do that and maybe that cause big work for transifex translators ...

@rakekniven What do you think about that ?

**Comment by Valdnet** [comment]
The translators can handle it 😁.
We have already translated all the names of languages and regions, the translators will also be able to translate the names of currencies 😉.

**Comment by baimard** [comment]
So why not, big work in prevision for me and after for the Transifex community :)

**Comment by rakekniven** [comment]
Hello, I vote against to make this translatable. 
How many times do you need to have listed currencies in your own language?

**Comment by rakekniven** [comment]
You can have it listed in your app without translation.
If you will add it for translation please make it one line for each currency.

**Comment by baimard** [comment]
> You can have it listed in your app without translation. If you will add it for translation please make it one line for each currency.

We discuss about translation in transifex of this list, and I ask you if it's an good idea :)

> Forgot to ask you another thing: Where did you get the list of currencies from?

random link in google ...

**Comment by rakekniven** [comment]
Actually there is no app in the nextcloud universe like yours regarding currencies.

Like stated in a previous post I would vote to not translate that list of currencies.

If it gets necessary in the future I strongly recommend to use international standards like ISO 4217 . See https://en.wikipedia.org/wiki/ISO_4217

**Comment by Valdnet** [comment]
If the app is fully translated, the currency should also be translated. Let me give you an example: If the application was in Chinese, we translate all text strings and leave the currency untranslated. I am curious how the users will choose their currency in Chinese.

> If it gets necessary in the future I strongly recommend to use international standards like ISO 4217 .

👍

@baimard Also pay attention to this: https://github.com/baimard/gestion/issues/60#issuecomment-1036267925.

**Comment by baimard** [comment]
Please open a New issue

**Comment by rakekniven** [comment]
Ok, arguments sounds valid.

As long as list is based on standards I am happy.

**Comment by baimard** [comment]
Added

embeded in 2.0.6

I also wait for : https://github.com/nextcloud/docker-ci/pull/355

**Comment by baimard** [comment]
https://github.com/nextcloud/docker-ci/pull/362

**Comment by baimard** [comment]
Done, lets go community !

**Comment by Valdnet** [comment]
Worse, when the community rebels on seeing so many currencies to translate 🤣.

**Comment by baimard** [comment]
Where is the conversation ?

**Comment by Valdnet** [comment]
Relax, there is no conversation yet 😉.

**Comment by baimard** [comment]
You're a robot ...

**Comment by baimard** [comment]
Translated in French :D very hard work !
