### ISSUE TITLE
[EN] Appearing information and help

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#150]
When selecting (switching) between the application menu, the following window appears briefly:

![obraz](https://user-images.githubusercontent.com/47037905/153633587-906a74ce-cddf-44fe-a3c5-d503d7fd1f92.png)

Apps:
Nextcloud 23.0.1
Gestion 2.0.2

**Comment by baimard** [comment]
Duplicate https://github.com/baimard/gestion/issues/142
