### ISSUE TITLE
[EN] There is no window with email setting

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#151]
The option to set up email is not shown. I only noticed when a window pops up momentarily while switching between application menus.

![obraz](https://user-images.githubusercontent.com/47037905/153636621-b5938df6-6e6f-4a88-9b40-ea92902417a2.png)

Apps:
Nextcloud 23.0.1
Gestion 2.0.2

**Comment by baimard** [comment]
It's because it's the global Email configuration of nextcloud and the mail of your user profile. I lock this issue and set a conversation if you don't have bug, do you agree ?

**Comment by Valdnet** [comment]
I found nothing like this in the user's global settings.

Where can I set the message content? If this content can be set at all.

**Comment by Valdnet** [comment]
> DO you speak about transifex possibility ?

It was about in-app editing.

When sending the e-mail, there is no information about the correct sending of the e-mail and about the sending error. The user doesn't really know if an invoice or quote has been sent.

**Comment by baimard** [comment]
With documentation that would be better ?

**Comment by Valdnet** [comment]
A message should appear informing you that the invoice or quote has been successfully sent.

**Comment by baimard** [comment]
Ok I will do that thank you :)

**Comment by Valdnet** [comment]
It would be good if such a correctly sent invoice or quote was confirmed in the table.

Example:

![obraz](https://user-images.githubusercontent.com/47037905/154918433-30bbbad9-1459-43be-b14b-36890206cab3.png)

**Comment by baimard** [comment]
it's complicated, because you can send many times the mail.

Is why I have created Status, when I send email I write in status "Mail send, wait answer 17/01/2022" (example)

**Comment by Valdnet** [comment]
> Is why I have created Status, when I send email I write in status "Mail send, wait answer 17/01/2022" (example)

A very good solution 😉.

**Comment by baimard** [comment]
I try to change something for this. What do you think ?

**Comment by baimard** [comment]
Done in production
