### ISSUE TITLE
[EN] Add a calendar

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#153]
I propose to add a calendar to choose the date in "Quote". This will make it easier for the user to enter the date.

![obraz](https://user-images.githubusercontent.com/47037905/153722979-e5e88101-3bda-4a47-b7be-2813a19b4081.png)

**Comment by Valdnet** [comment]
> in this page ? https://next.cybercorp.fr/apps/gestion/devis

???

Add the calendar, which is next to "Payment date" 😉.

![obraz](https://user-images.githubusercontent.com/47037905/153723500-ddca61cb-0bd5-4ab2-b375-92560223330a.png)

**Comment by baimard** [comment]
I don't understand because I have calendar in quote in my version ???

**Comment by Valdnet** [comment]
I have version 2.0.2. This is what it is like in the Nextcloud Store.

**Comment by baimard** [comment]
This calendar is present from version 1 :D

**Comment by Valdnet** [comment]
For me it does not appear for "Quote". I am using Firefox 97.0.
