### ISSUE TITLE
[EN] Error installing the new version

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#157]
When installing the new version 2.0.4, an error occurs:

![obraz](https://user-images.githubusercontent.com/47037905/153724618-5161eec8-725e-4ffd-81e3-8c12e397f2bd.png)

**Comment by baimard** [comment]
Yes it's because of the PHP version :)

**Comment by Valdnet** [comment]
I changed the PHP version settings in the .htaccess file and did not go back to version 7.4. I am closing the issue.
