### ISSUE TITLE
[EN] Add a text string to translate

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#158]
Add the following string to your translation and change `Annuler` -> `Cancel`.

https://github.com/baimard/gestion/blob/dd087361513c911944d5c569239ae707712f127b/src/js/modules/ajaxRequest.mjs#L173

![obraz](https://user-images.githubusercontent.com/47037905/153726185-a74c5918-0d0e-4b4b-a6e0-5efde83ac5e6.png)

**Comment by baimard** [comment]
Embeded 2.0.5
