### ISSUE TITLE
[EN] Adding products

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#159]
When adding another product, the product list cannot be selected:

![obraz](https://user-images.githubusercontent.com/47037905/153726368-79c0587c-fdcf-4707-8909-78aebf57752f.png)

With the first product, the product list is duplicated:

![obraz](https://user-images.githubusercontent.com/47037905/153726428-41855eaf-044f-45c9-9335-9a9c28d2abcf.png)

When adding a product, there is no window with the option to select a product. You now need to click twice to see the selection window.

![obraz](https://user-images.githubusercontent.com/47037905/153726473-14105260-ea75-43fe-aaad-0e3f879f8afa.png)

A product selection window should appear with the description "Choose product":

![obraz](https://user-images.githubusercontent.com/47037905/153726551-4a4d9b2f-ca98-42f5-af38-f7e8fbdfeee7.png)

This is currently not understandable by the user.

**Comment by baimard** [comment]
Quote/invoice ?

**Comment by Valdnet** [comment]
> What's strange is if you wan't to reproduce that from bottom to top product and not from top to bottom !

You cannot predict the user's handling of the application 😁.

This is why the application is tested :wink:.

**Comment by baimard** [comment]
I need to do this modification ... :)
