### ISSUE TITLE
[EN] Center data in a table

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#160]
Please center the data in the table:

![obraz](https://user-images.githubusercontent.com/47037905/153726908-61aa419a-f3fc-4d18-be38-2bb83ec11158.png)

**Comment by baimard** [comment]
Center Year, but number align right ? maybe better ?

**Comment by Valdnet** [comment]
Yes you are right 👍. The year should be centered and the numbers to the right.

**Comment by baimard** [comment]
Embeded 2.0.5
