### ISSUE TITLE
[EN] Change to plural

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#161]
I suggest changing the following text strings in the application menu to plural:

![obraz](https://user-images.githubusercontent.com/47037905/153727303-83872365-a2f4-4c00-9dac-555b68525daf.png)

Customer -> Customers
Quote -> Quotes
Invoice -> Invoices
Product -> Products
Information -> Informations

**Comment by baimard** [comment]
There is no rule for that. In French you speak in general so you use singular. In english after reading some articles about this subject, there is no rule.

My suggest is that you can use plural in your langage ? (transifex?)

https://ux.stackexchange.com/questions/110325/plural-or-singular-navigational-menu-options
https://ux.stackexchange.com/questions/5124/what-are-good-rules-for-naming-menu-items

**Comment by Valdnet** [comment]
I will give you an example: If you have several files that you cannot see directly in the application. To display them, you use the menu for them. And now how you describe this menu as "File" or "Files". If you describe it as "File" the user is informed that in this menu you only expect one file, if you describe "Files", the user is already informed that there may be multiple files. It's okay if it only sees one file named "Files", but if it sees many files named "File" you might be a little surprised.
