### ISSUE TITLE
[EN] Strange characters in the currency name

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#163]
There are strange characters in the text strings in the following currencies:

![obraz](https://user-images.githubusercontent.com/47037905/153609030-74e15772-3a6f-4ed1-9c86-21517a5c6ace.png)

![obraz](https://user-images.githubusercontent.com/47037905/153609193-e8d9cb47-bed1-4460-841a-936c6123a960.png)

**Comment by baimard** [comment]
Embeded 2.0.5
