### ISSUE TITLE
[EN] First launch of application

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#167]
When the application is launched for the first time after installation, an information window appears. After clicking on "My Company" the window **reappears**.

![obraz](https://user-images.githubusercontent.com/47037905/154024998-5fa6de7d-f656-49fa-b248-7b8bb1acdffc.png)

Apps:
Nextcloud 23.0.1
Gestion 2.0.4

**Comment by baimard** [comment]
embeded in 2.0.5
