### ISSUE TITLE
[EN] Joining strings together is evil

### ISSUE THREAD

**Issue by rakekniven** [baimard/gestion#17]
https://github.com/baimard/gestion/blob/2e6bf842bc729ddcc9ca77e1ef5aaa51d1c284aa/src/js/main.js#L25

please do not join single strings to a sentence.
The translator at Transifex does not know about it until he looks at the source code. Only a few do.

And the worst: in some language the order of a sentence is different e.g. in german the verbs are often at the end. In chinese they are placed nearly at the beginning.

Solution:
Use placeholders like the many other apps do.

**Comment by Valdnet** [comment]
This is translators testing :smile:.

**Comment by baimard** [comment]
https://open.spotify.com/track/2iioOQ83EXoy7yMpy0UNx4?si=a0bdf44eccc14a79

**Comment by baimard** [comment]
@rakekniven do you have the template to add vars in a translated sentence ?

**Comment by baimard** [comment]
Solve in last commit.

Is that good for you ?

**Comment by rakekniven** [comment]
Yes, very good!
