### ISSUE TITLE
[EN] Column width in "Product"

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#175]
I suggest reducing the width of the columns in "Product" for "Unit price without VAT" and "Actions":

![obraz](https://user-images.githubusercontent.com/47037905/154310826-de2cc3ee-ca79-4fff-9245-66f0d3974b03.png)

**Comment by baimard** [comment]
Width is auto in datatable, it's strange because in my screen that appear reduce ... 
![Capture d’écran de 2022-02-16 19-26-43](https://user-images.githubusercontent.com/7591697/154331526-8c63f2ab-b1e9-440d-8639-961bbe1c4ce5.png)

**Comment by Valdnet** [comment]
I am using Firefox 97.0.
