### ISSUE TITLE
[EN] Invoice number and VAT rate

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#18]
Since the application is not working properly on my instance and I cannot test it well, I have a question regarding the invoice number and VAT rates.

- I noticed that the invoice numbering order is not generated automatically. I suggest that you can set the initial invoice number and a fixed value to keep the numbering continuous. I mean, that this value of variable `xxx` would be generated automatically, while the constant value `yyy` was assigned by the user and did not change.

Examples:
xxx/yyy - 1/2021
xxx/yyy - 2/2021
xxx/yyy - 3/2021

- The second thing I wanted to ask about is the VAT rate setting. Is it possible to set VAT rates in advance, so that when adding goods, you can select only the VAT rates that were previously determined?

The next thing is that in Polish tax law there is an additional VAT rate "exempt" from VAT. This is nothing but 0 VAT, but the goods must be sold and marked "exempt".

Is it possible to add such a VAT rate?

**Comment by baimard** [comment]
Dear,

thank you for your comment.

for your first question : 

I don't know if it's really needed, Actually it's a simple free text. So you can set whatever you want

**Comment by Valdnet** [comment]
> I don't know if it's really needed, Actually it's a simple free text. So you can set whatever you want

Yes, but you can make mistakes with the invoice numbering. I don't know about French law, but in Poland the numbering of invoices is very important. It cannot be repeated.

**Comment by baimard** [comment]
> > I don't know if it's really needed, Actually it's a simple free text. So you can set whatever you want
> 
> Yes, but you can make mistakes with the invoice numbering. I don't know about French law, but in Poland the numbering of invoices is very important. It cannot be repeated.

It's exactly the same in France, and if you need to correct something, it may be better if you're free in the application.

But I understand your need and I will try to integrate an intermediate solution

**Comment by baimard** [comment]
I will add a comment zone at the bottom of the application for laws declarations

**Comment by digitalrevisor** [comment]
Hello.  Im a auditor / accountant from Norway.
The rules in whole eurpoe is that Invoice numbers must be generated continuously without being manipulated in order to be used in legal business. This has to do with completeness control by the authorities. Furthermore, there should be an input field for code in settings for VAT rate and which the user can add to the product. To meet the minimum requirements of a fantastic software such as this currency must not be behind the amount but in a separate editable field on the product. This is displayed on the product line. I guess this is not a big job with changes for someone who has made such a nice application.

Finally: It would be a scoop it this application can talk to Timemanager / Timetracker in NC.
Nice work!

**Comment by Valdnet** [comment]
@digitalrevisor I agree with you 👍. Numbering should be generated automatically. Only additional markings can be edited, such as the year or adding the company's branch number, etc., which will appear next to the invoice number.

**Comment by timkrief** [comment]
I started working on vat rate in #31 it's taken into account in the calculation, the value is just "0" right now :sweat_smile: . but it could be changed by adding an input field somewhere

**Comment by baimard** [comment]
VAT default OK
Comment zone OK

**Comment by digitalrevisor** [comment]
> I understand all your comments, but we have different situation in different country.
> 
> Example : In france you just have to proof that all your invoices and quotes number are not interrupt.
> 
> So please just tell me what you need, in a list and I will integrate in the application.
> 
> Thank you for all your encouragement.

Yes, thats what I mean.  To proof that all your invoices and quotes number are not interrupt. The code has to be automatic lock the order of invoicenumbers. So that users only can make creditinvoices instead of being abel to delete the invoice.

**Comment by baimard** [comment]
It's in my task list.

**Comment by digitalrevisor** [comment]
No. its not legal in EU. It schould not be possible to manipulate the sequens og invoicenumbers.  This has to do with completeness control by the authorities. Furthermore, there should be an input field for code in settings for VAT rate and which the user can add to the product. To meet the minimum requirements of a fantastic software such as this currency must not be behind the amount but in a separate editable field on the product, not company.

**Comment by baimard** [comment]
In France the Law Say : invoice have to be a sequence not interrupt. Anyway, you Can manipulate directly the database. So in IT tout can't be sur that the invoice number hare not manipulate.

Do you have an example of that :"Furthermore, there should be an input field for code in settings for VAT rate and which the user can add to the product", I'm actualy developping the vat part

Don't understand the last part of your message

**Comment by digitalrevisor** [comment]
Ok. This I supose: "To meet the minimum requirements of a fantastic software such as this currency must not be behind the amount but in a separate editable field on the product, not company."
I try to write it in another way:  Currency(NOK - $ - £)  can be editable behind unit price on the product tab - Not behind ammount in invoice. The product specs will show up in quota / invoices product line.   Was that understandable?

**Comment by baimard** [comment]
> Ok. This I supose: "To meet the minimum requirements of a fantastic software such as this currency must not be behind the amount but in a separate editable field on the product, not company." I try to write it in another way: Currency(NOK - $ - £) can be editable behind unit price on the product tab - Not behind ammount in invoice. The product specs will show up in quota / invoices product line. Was that understandable?

I'm sorry I really don't understand, IS it possible to make a screen or a template ? Sorry 😂

**Comment by digitalrevisor** [comment]
Have a look at this. Download the file please.
https://demo.digitalrevisor.eu/index.php/s/S2gzPjTgSASsaWM

**Comment by digitalrevisor** [comment]
New file: Some changes.  https://demo.digitalrevisor.eu/index.php/s/3LnGeaPH9rkJM6A

**Comment by baimard** [comment]
Aaaaaaaa you mean discount. The currency it is not that !!! It's the system of monney !

I'm working on the discounts :)

**Comment by digitalrevisor** [comment]
Not discount, but Vat.

**Comment by digitalrevisor** [comment]
Each product can have different Vat rate (%)

**Comment by baimard** [comment]
You have different vat for your product in own quote ?

**Comment by digitalrevisor** [comment]
yes yes. Right.

**Comment by baimard** [comment]
Ok all is Taken into account. Thank you for your time and for the explanation

**Comment by digitalrevisor** [comment]
Product A can have 25 % vat rate. Product B can have 15 % Vat rate.

**Comment by Valdnet** [comment]
Still in the new version 1.2.2, invoice numbers are not generated in a fixed order.
