### ISSUE TITLE
Make addresses multiline text fields

### ISSUE THREAD

**Issue by Moini** [baimard/gestion#180]
Addresses can currently only be on a single line. This is pretty uncommon. 

Please allow entering address information with multiple lines, by providing a text area instead of a text field.

**Comment by baimard** [comment]
This is not a bug, this need to be open in a new discussion : https://github.com/baimard/gestion/discussions

Also, to prevent a duplicate discussion, please take the time to read all the opens discussions.

**Comment by Moini** [comment]
See https://github.com/github/feedback/discussions/2952 for how to convert an issue into a discussion. Really, you can also use a tag 'feature request'. This is what people commonly do.

It is a bug for me, though, as in Germany, we write addresses into multiple lines. It looks very odd to have to put them on a single line, especially for long addresses, like institutions, universities etc.
