### ISSUE TITLE
Flashing of instructions page on each page load

### ISSUE THREAD

**Issue by Moini** [baimard/gestion#183]
Everytime I click on any of the menu items on the left, for a short time, the default instructions page is shown until the proper content is loaded. This is very distracting.

Please show a loading animation or an empty page instead until the content is available.

**Comment by baimard** [comment]
When you discover a new project, Maybe you could read everythings .. 

DUPLICAT : https://github.com/baimard/gestion/issues/142

**Comment by baimard** [comment]
Duplicate of #142

When you discover a new project, Maybe you could read everythings ..

**Comment by Moini** [comment]
Merci, I hadn't seen that.
