### ISSUE TITLE
[EN] Internal server error

### ISSUE THREAD

**Issue by bread-on-toast** [baimard/gestion#19]
Hi,
I tried to install your app, however I get the following error (in the logging section):
`OCP\AppFramework\QueryException: Could not resolve OCA\Gestion\Controller\PageController! Class OCA\Gestion\Db\Bdd does not exist

    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 126:

    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Gestio ... r")

    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 455:

    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Gestio ... r")

    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 427:

    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Gestio ... r")

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 139:

    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Gestio ... r")

    /var/www/nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("OCA\\Gestio ... r", "index", OC\AppFramew ... {}, { action: nu ... "})

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/gestion/")

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()`
    

I assume I am missing some dependences?

**Comment by baimard** [comment]
look like a file is missing in your directory. How do you have install the application

**Comment by bread-on-toast** [comment]
I tried installing it via the nextcloud GUI as well as manually copying the files into the apps folder. Both were unsuccessful.

**Comment by baimard** [comment]
Looks very strange.

Could you please share me your setup ?

**Comment by bread-on-toast** [comment]
Sure:
Ubuntu 20.04.3 LTS
nginx 1.18.0
php-fpm7.2

**Comment by baimard** [comment]
Just could you please confirm that you have this file : 

Gestion\Db\Bdd.php file ?

**Comment by bread-on-toast** [comment]
I can find the following file:

/apps/gestion/lib/Db/Bdd.php

**Comment by baimard** [comment]
I will serch the bugs. Thank you for repporting !

**Comment by baimard** [comment]
What is your version of nextcloud ?

**Comment by bread-on-toast** [comment]
it's 20.0.3
I will try to upgrade to a more recent one today

**Comment by bread-on-toast** [comment]
I updated to the most recent version of nextcloud an installed php-7.4. This solved the problem.

**Comment by baimard** [comment]
Maybe the application is not compatible with nextcloud 20, I will verify. Thank you !!
