### ISSUE TITLE
Unreadable fields with dark mode

### ISSUE THREAD

**Issue by infra-monkey** [baimard/gestion#190]
**Describe the bug**
If the dark mode is enabled on nextcloud, the first field for each page is unreadable.

**To Reproduce**
1. enable dark mode
2. go to the customers or quotes page
3. The first column's fields are unreadable

**Expected behavior**
The page should use the defined backgroud colors and text colors (or shades of them if needed) so it stays consistent with the applied theme.

**Screenshots**
![Screenshot_gestion](https://user-images.githubusercontent.com/43171889/155369733-1fb7085c-bde5-44de-8cb5-ec7077a2f2c4.png)

![Screenshot_gestion2](https://user-images.githubusercontent.com/43171889/155370588-97d4205b-6290-48f5-a8d0-14fc418916de.png)

**Desktop (please complete the following information):**
 - OS: Linux Fedora 35
 - Browser: Brave 1.35.103 / Firefox 97.0
 - Version: Gestion 2.0.5

**Comment by baimard** [comment]
thank you for reporting, I will fix that !

**Comment by infra-monkey** [comment]
> thank you for reporting, I will fix that !

Thank you for makeing the app and reacting so quickly :smile:

**Comment by baimard** [comment]
:)
