### ISSUE TITLE
impossible de lancer l'application Gestion - Erreur Interne du Serveur

### ISSUE THREAD

**Issue by zouma83** [baimard/gestion#2]
Bonjour :)

crash de l'application au lancement
"Erreur interne du serveur"

Erreur interne du serveur

Le serveur est incapable d'exécuter votre requête.

Si cela se reproduit, veuillez envoyer les détails techniques ci-dessous à l'administrateur du serveur.

Le fichier journal du serveur peut fournir plus de renseignements.
Renseignements techniques

    Adresse distante : x.y.z.z
    ID de la demande : axL7GfnFlklFPkw93vIp

[index] Error: ParseError: syntax error, unexpected 'String' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at <<closure>>

 0. /var/www/nextcloud/lib/composer/composer/ClassLoader.php line 346
    Composer\Autoload\includeFile("/var/www/nextcl ... p")
 1. <<closure>>
    Composer\Autoload\ClassLoader->loadClass("OCA\\Gestion\\Db\\Bdd")
 2. <<closure>>
    spl_autoload_call("OCA\\Gestion\\Db\\Bdd")
 3. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 107
    ReflectionClass->__construct("OCA\\Gestion\\Db\\Bdd")
 4. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 126
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Gestion\\Db\\Bdd")
 5. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 459
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Gestion\\Db\\Bdd")
 6. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 431
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Gestion\\Db\\Bdd")
 7. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 87
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Gestion\\Db\\Bdd", true)
 8. <<closure>>
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
 9. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 101
    array_map(Closure {}, [ReflectionParam ... }])
10. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 109
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
11. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 126
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Gestion\\C ... r")
12. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 459
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Gestion\\C ... r")
13. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 431
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Gestion\\C ... r")
14. /var/www/nextcloud/lib/private/AppFramework/App.php line 144
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Gestion\\C ... r")
15. /var/www/nextcloud/lib/private/Route/Router.php line 302
    OC\AppFramework\App::main("OCA\\Gestion\\C ... r", "index", OC\AppFramework\ ... {}, {_route: "gestion.page.index"})
16. /var/www/nextcloud/lib/base.php line 993
    OC\Route\Router->match("/apps/gestion/")
17. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /apps/gestion/
from x.y.z.z by _adm_XYZ at 2021-07-30T17:55:18+00:00

Nextcloud 21.0.3
NGinx
PHP-FPM 7.3
MariaDB

Apps List:
 Accessibility
1.7.0
Mises en avant
Activity
2.14.3
Mises en avant
Announcement center
5.0.0
Mises en avant
Antivirus for files
3.2.1
AppOrder
0.13.0
Audio Player
3.1.0
Audio Player - ID3 Editor (add-on)
0.3.0
Breeze Dark
21.0.9
Calendar
2.3.1
Circles
0.21.3
Collabora Online
4.2.1
Collabora Online - Built-in CODE Server
6.4.1004
Collaborative tags
1.11.0
Comments
1.11.0
Contacts
4.0.1
Contacts Interaction
1.2.0
Cookbook
0.8.4
Dashboard
7.1.0
Data Request
1.8.0
Deleted files
1.11.0
Draw.io
1.0.1
EPUB/CBZ/PDF ebook reader
1.4.6
External sites
3.8.2
Extract
1.3.2
Federation
1.11.0
File sharing
1.13.1
First run wizard
2.10.0
Gestion
1.0.4
Google integration
1.0.2
Group folders
9.0.2
Log Reader
2.6.0
Mail
1.10.2
Maps
0.1.9
Metadata
0.14.0
Monitoring
1.11.0
Nextcloud announcements
1.10.0
Notes
4.1.0
Notifications
2.9.0
PDF viewer
2.1.0
Photos
1.3.0
Plain text editor
2.14.0
Privacy
1.5.0
Ransomware protection
1.11.0
Recommendations
1.0.0
Registration
1.3.0
Right click
1.0.0
Share by mail
1.11.0
Splash
1.2.3
Support
1.4.0
Talk
11.3.1
Text
3.2.0
Theming
1.12.0
Two-Factor TOTP Provider
6.1.0
Update notification
1.11.0
Usage survey
1.9.0
User status
1.1.1
Versions
1.14.0
Video converter
1.0.2
Video player
1.10.0
Weather
1.7.5
Weather status
1.1.0

d'avance merci pour le retour
et merci aussi pour le projet Gestion ;)
FM

**Comment by zouma83** [comment]
ça ressemble à une coquille 7.3
7.4 corrigerai le probleme semble t'il

**Comment by baimard** [comment]
Bonjour,

Merci beaucoup pour ton bug report, je vais regarder ça de plus prêt dans le weekend.

Merci également de ton intérêt pour mon application, je suis très heureux de voir qu'au moins une personne s'y est intéressé !

As tu finalement pu la lancer ?

**Comment by zouma83** [comment]
Bonsoir :)

oui je viens de basculer php 8.0 !
it works....

nextcloud ok
gestion ok ;)

top ! problème resolu...

php - fpm 7.3 -> 7.4 -> 8...
quelques platres...
& so good... nextcloud ok, cron ok, gestion ok journaux ok

;)

**Comment by zouma83** [comment]
+1 le passage au php8 fait que HPB marche toujours en udp et désormais également en tcp ???
je voulais upgrade depusi un moment....
merci à toi de m'avoir trouver la motive

gestion = php 7.4 minimum !

**Comment by baimard** [comment]
Merci du retour je vais monter un environnement par curiosité ! Je marque la sujet comme résolu en tout cas merci. N'hésite pas à me contacter si tu as besoin de fonctionnalités. Je suis très curieux d'avoir des retours utilisateurs.

**Comment by baimard** [comment]
Bonjour,

Suite à cette erreur avez vous pu utiliser l'application normalement ?

**Comment by zouma83** [comment]
Bonjour,

j'ai fait quelques tests sommaires => ok
le principal utilisateur potentiel de cette appli devrait sous peu la mettre à l'épreuve...
une idée pour comment intégrer un logo ?
pour info je suis resté en php 8 malgré la precau NC 7.4...

**Comment by baimard** [comment]
PHP 8 s'est ok.

Pour l'intégration du logo, il faut que je le développe :) c'était prévu dans ma tête. Je vais le mettre dans la todo.
