### ISSUE TITLE
[EN] special characters in adress, product name etc

### ISSUE THREAD

**Issue by bread-on-toast** [baimard/gestion#20]
Hi,
I came across the following problem:
When I use characters such as german uml like auts, but also something like an é, it will turn up as its html representation. 
Eg ä becomes &auml; and é becomes &eacute;
Also newlines are removed. Is there a way to fix this?

**Comment by baimard** [comment]
> Also newlines are removed. Is there a way to fix this?

For this, it's a feature,

could you please share me a screen of your problem ?
