### ISSUE TITLE
[FR] Erreur DB id → 'Not null violation' - PostgresSQL

### ISSUE THREAD

**Issue by DT77-A** [baimard/gestion#21]
Bonjour  Benjamin,

Merci pour l'application et le temps que tu passes. Je viens de finir sa mise en route sur PostgresSQL.

Je te fait remonter l'erreur suivante 'Not null violation' → 'id'. lors de la création de l'entreprise (oc_gestion_configuration) ou d'un insert dans une autre table. 

L'id ne peut pas être défini sur NULL pour les bases de donnés PostgresSQL, il doit être défini sur 0 pour s'incrémenter.

Dans le fichier lib → Db → Bdd.php,
J'ai remplacé :  INSER INTO  x ('id',... ) VALUES (NULL, ....); par INSER INTO  x ('id',... ) VALUES (0, ....);

Log de l'erreur :
#Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "id" violates not-null constraint DETAIL: Failing row contains (null, Nom, Prénom, Siret, Société, Téléphone, Email, Adresse, User).

Je pense que ça va aider des utilisateurs 👍 

---

Hello Benjamin,

Tks for your application. I tried to install with PostgresSql but there is a bug.

ID null return an error so : 

- I change in lib/Db/Bdd.php ID value in INSERT request to 0 : 
Like this : INSER INTO  x ('id',... ) VALUES (NULL, ....); par INSER INTO  x ('id',... ) VALUES (0, ....);

**Comment by baimard** [comment]
Bonjour @DT77-A,

Merci pour ton retour c'est vraiment agréable d'avoir des tickets utilisateurs et de voir que cette application n'est pas un coup d'épée dans l'eau.

L'erreur que j'ai faite dans l'application c'est que je passe hors doctrine. Il faudra que je réajuste tout ça. En tout cas merci pour les utilisateurs.

Pourrais tu essayer sans mettre la colonne ID ? car je crois que dans Mariadb/Mysql ça fonctionne ainsi.

**Comment by DT77-A** [comment]
@baimard, 

Sans utiliser la colonne id, c'est fonctionnel 👍

**Comment by baimard** [comment]
Je vais modifier dans ce sens après contrôle que ça fonctionne dans Mysql :) Merci

**Comment by stoutouloutou** [comment]
Bonjour,
ayant eu la meme erreur, j'ai modifié le fichier Bdd.pho come indiqué, ce qui débloque la création d'entreprise, mais génère un autre probleme : je ne peux ajouter qu'un seul produit !
il me renvoie l'erreur "ERROR:  duplicate key value violates unique constraint" quand j'essaie d'en ajouter un.
Bref, il semble qu'il n'incrémente pas l'ID. Je peux modifier la requet INSERT pour mettre un ID à 1, 2, 3, ...  à chaque nouveau produit, mais c'est galère !
Merci de votre aide !

**Comment by stoutouloutou** [comment]
Je m'auto corrige : en enlevant la colonne ID, ca semble marcher !

**Comment by baimard** [comment]
J'ai un accroissement d'activité pour la fin d'année, je m'occupe de cela bientot.

**Comment by baimard** [comment]
Normalement, tous les problèmes de ce côté son résolu.
