### ISSUE TITLE
Alphabetical sorting of currencies

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#213]
Currency names should be sorted alphabetically. For the Polish language, it looks like this:

![obraz](https://user-images.githubusercontent.com/47037905/158554274-83a8fb2a-023e-4a8e-a8d1-475005213831.png)

App:
Gestion 2.0.8

**Comment by baimard** [comment]
In next release 2.0.9 :)

**Comment by baimard** [comment]
Version in production

**Comment by Valdnet** [comment]
Works correctly 👍. Thanks 😉.

**Comment by baimard** [comment]
Very nice suggestion, :) thanks you too
