### ISSUE TITLE
Inactive window in settings

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#214]
After selecting an option in the application settings, the window appears inactive. After refreshing the page, you can select the appropriate option again.

![obraz](https://user-images.githubusercontent.com/47037905/158556614-43d54943-7069-4ace-90bf-a2467d01e6b8.png)

App:
Gestion 2.0.8

**Comment by baimard** [comment]
Quick fix, just refresh the page. It's due to pure js function. I will fix in next release.

Thank you @Valdnet I hope you're fine !

**Comment by Valdnet** [comment]
> I hope you're fine !

Yes. I spend a lot of time testing applications and translating them 😉.

**Comment by baimard** [comment]
OK in V2.0.8 after clean cache, do you confirm ?

**Comment by baimard** [comment]
Version in production

**Comment by Valdnet** [comment]
Works correctly 👍. Thanks 😉.
