### ISSUE TITLE
[FR] click on open the page refreshes and returns to the nextcloud dashboard

### ISSUE THREAD

**Issue by baimard** [baimard/gestion#218]
### Discussed in https://github.com/baimard/gestion/discussions/217

<div type='discussions-op-text'>

<sup>Originally posted by **Flavien124** March 18, 2022</sup>
Hello, I manage to create a customer, a product, an estimate or an invoice, but when I click on open (invoice or estimate), the page refreshes and returns to the nextcloud dashboard
I attach my logs

sorry I use google translate, I'm french

 - Openmediavault Nextcloud docker, with letsencrypt
 - Brave Browser
 - last version

![Capture_decran_2022-03-17_221510](https://user-images.githubusercontent.com/101864773/158972344-61d8e225-4d79-457e-ae63-4599ece70c8a.png)

</div>

**Comment by Flavien124** [comment]
Bonjour et merci pour ta reponse, Voila le maximun d'info que j'ai 
Ma base de donnée : SQLite
version de nextcloud : [Nextcloud Hub II](https://nextcloud.com/) (23.0.2)
Version Gestion : 2.0.8
Installer via Portenaire et Docker compose depuis Openmediavault 6.0.17-1 (Shaitan)
Machine Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz, 8 Go de RAM DDR3

**Comment by baimard** [comment]
Tu as utilisé un plugin pour les mails ?

**Comment by Flavien124** [comment]
J'utilise uniquement L'appliquation Mail integré a nextcloud avec mon adresse Gmail, donc je pense que non, tout de moin je n'est rien installer a coté

**Comment by baimard** [comment]
Ah mais as tu configuré le serveur de mail dans les paramètres serveurs ?

**Comment by Flavien124** [comment]
Je vois pas exactement de quoi tu parle, mais j'ai mis mon mail sur mon profil, sur l'application Mail integré a Nextcloud ( ca marche bien en réception- envois), J'ai même testé en désactivant et supprimant l'application Mail, même résultat même message d'erreur

**Comment by baimard** [comment]
Est ce que dans Paramètre/Administration/Paramètre de base, tu as configuré les mails ?

**Comment by Flavien124** [comment]
Bonjour et merci pour ta réponse, quel database conseil tu ?

**Comment by baimard** [comment]
Je développe mon application avec MariaDB :). Même si je vais quand même essayer d'assurer la compatibilité avec toutes les bases, je recommande celle là :)

**Comment by baimard** [comment]
peux tu me donner l'image exacte que tu utilises ?

**Comment by baimard** [comment]
je pense que j'ai vu

**Comment by Flavien124** [comment]
Bonsoir, je viens de changer ma databse par mariab via une clean reinstalle, voici le tuto exacte que j'ai utilisé pour installer nextcloud,
https://forum.openmediavault.org/index.php?thread/28216-how-to-nextcloud-with-swag-letsencrypt-using-omv-and-docker-compose/

**Comment by baimard** [comment]
J'ai trouvé l'anomalie, ça va peut être rien changer.

**Comment by Flavien124** [comment]
Effectivement j'en est chier a tout changer et ca n'a rien fais, l'erreur viens de chez moi ? une piste que je puisse regler ca ? merci

**Comment by baimard** [comment]
Non ça vient de mon code je vais envoyer la version 2.0.9 dans 30 minutes, demain matin elle sera opérationnel.

**Comment by Flavien124** [comment]
au top merci, je vous tiens au courant, une petite suggestion, pour les micro entrepreneur, nous avons besoin de mettre 
La mention « TVA non applicable - article 293 B du CGI » a la place du taux de tva, je sais pas si cela est possible
par avance encore merci 
Flavien

**Comment by baimard** [comment]
Taux de tva à 0%

et dans les mentions légales dans configuration tu configures.

![Capture d’écran de 2022-03-20 23-24-51](https://user-images.githubusercontent.com/7591697/159188605-9db23fb8-29bb-4664-9206-9151f9bd8634.png)

Il va falloir que je fasse une note explicative.

**Comment by baimard** [comment]
Bonjour Flavien la version est disponible ce matin.

**Comment by Flavien124** [comment]
Bonjour, j'ai bien fait la mise a jour, même résultat avec des logs diffèrent
un chmos a faire quelque part ? 
quand vous parler de vider les cache, vous parlez des cache navigateur ou de l'appli, je ne sais pas faire si vous parlez des cache de l'appliquation
![Capture d’écran 2022-03-21 143447](https://user-images.githubusercontent.com/101864773/159272468-35399121-8012-43d9-95f8-5205216b3e8b.png)

**Comment by baimard** [comment]
Ça n'est pas un bug de mon application mais de circle il y a vraiment quelque chose de bizarre avec ton instance.

**Comment by baimard** [comment]
tu as ton fichier docker compose ?

**Comment by baimard** [comment]
Plus d'information
