### ISSUE TITLE
Erreur à l'installation

### ISSUE THREAD

**Issue by Nakio195** [baimard/gestion#22]
Bonjour Benjamin, tout d'abord merci de prendre du temps pour développer cette application qui j'en suis sur me seras utile !

Seulement j'ai un problème à l'installation. J'ai d'abord tenté une install depuis NX 21.0.4 via le gestionnaire d'application puis après une mise à jour vers NX 22.1.1 j'ai la même erreur, je tombe sur une page d'erreur interne de Nextcloud et voici le log de cette même erreur : 

`Error	index	ParseError: syntax error, unexpected 'String' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

    /home/nextcloud/html/nextcloud/lib/composer/composer/ClassLoader.php - line 346:

    Composer\Autoload\includeFile("/home/nextc ... p")

    <<closure>>

    Composer\Autoload\ClassLoader->loadClass("OCA\\Gestion\\Db\\Bdd")

    <<closure>>

    spl_autoload_call("OCA\\Gestion\\Db\\Bdd")

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 112:

    ReflectionClass->__construct("OCA\\Gestion\\Db\\Bdd")

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:

    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Gestion\\Db\\Bdd")

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 460:

    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Gestion\\Db\\Bdd")

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 432:

    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Gestion\\Db\\Bdd")

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 87:

    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Gestion\\Db\\Bdd", true)

    <<closure>>

    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 106:

    array_map(Closure {}, [ Reflection ... "])

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 114:

    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionCl ... "})

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:

    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Gestio ... r")

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 460:

    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Gestio ... r")

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 432:

    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Gestio ... r")

    /home/nextcloud/html/nextcloud/lib/private/AppFramework/App.php - line 143:

    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Gestio ... r")

    /home/nextcloud/html/nextcloud/lib/private/Route/Router.php - line 301:

    OC\AppFramework\App::main("OCA\\Gestio ... r", "index", OC\AppFramew ... {}, { _route: "gestion.page.index"})

    /home/nextcloud/html/nextcloud/lib/base.php - line 1000:

    OC\Route\Router->match("/apps/gestion/")

    /home/nextcloud/html/nextcloud/index.php - line 36:

    OC::handleRequest()`

Si tu as une piste de solution je suis preneur !

Merci !

- Nextcloud 21.0.4 / 22.1.1
- Apache2 2.4
- PHP 7.3 fpm-mod
- MariaDB 10.3.27
- Debian 10

**Comment by baimard** [comment]
Bonjour, merci de ton retour, pourrais tu essayer avec PHP 7.4 ?

⁣cordialement,
Benjamin AIMARD​

Le 13 sept. 2021 à 15:59, à 15:59, "Théo HYVON" ***@***.***> a écrit:

**Comment by baimard** [comment]
Il va falloir que je le note dans les pré requis

⁣cordialement,
Benjamin AIMARD​

Le 13 sept. 2021 à 17:47, à 17:47, "Théo HYVON" ***@***.***> a écrit:
