### ISSUE TITLE
[EN] Remove/replace non existing currencies

### ISSUE THREAD

**Issue by p-bo** [baimard/gestion#223]
Hi,
it seems, that source of list of currencies used was not up to date. For instance:
 
Replaced by Euro:
 Belgian Franc
 Estonian kroon
 German Mark
 Greek Drachma
 Italian Lira
 Latvian lats
 Lithuanian Litas
 Slovak Koruna

Replaced by U.S. dollar:
 Salvadoran colón

Cuban convertible peso - replaced by Cuban peso in 2021
(https://en.wikipedia.org/wiki/Cuban_peso)

Wrong name:
Icelandic Kana -> Icelandic króna

Nicaraguan Cadoba -> Nicaraguan córdoba

Qatari Rial -> Qatari riyal

Then there is some very special monetary unit, which using is probably out of scope of any users of this app - see:
https://en.wikipedia.org/wiki/Special_drawing_rights

Could it be possible to fix this please? Thanks :-)

**Comment by baimard** [comment]
Thank you, yesterday when I have translated the list in french from transifex, I was asking my self about European monetaries. The questions was exactly the same as yours. So you're probably right and I will change that in v2.0.10.

Idem for all of your pertinent information, thank you !

**Comment by p-bo** [comment]
Glad to help :-)
It seems, that definite (sourcing from authoritative sources) source could by Wikipedia:
https://en.wikipedia.org/wiki/ISO_4217
(active normalized and informal _active_ currencies, including major cryptocurrencies)
Table of official currencies is from year 2021, thus Cuban peso unification isn't reflected here yet.
Also most of X-currencies (for precious metals, for instance) is no use there probably.

**Comment by baimard** [comment]
Done
2.1.0
