### ISSUE TITLE
Auto invoice number not working

### ISSUE THREAD

**Issue by CptPlastic** [baimard/gestion#237]
**Describe the bug**
Auto number is not creating a number automatically.

**To Reproduce**
1. Enable Auto Invoice Number in settings
2. Click Create new Invoice
3. Should see a number generated

**Expected behavior**
Invoice or quote should have numbers generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/1010444/165660276-b6515723-eb27-4c41-8207-9ef7a04dc1ef.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [100.0]

**Comment by CptPlastic** [comment]
![image](https://user-images.githubusercontent.com/1010444/165660575-7bfe56c8-3299-4fea-b6fa-14795e0bae01.png)

**Comment by baimard** [comment]
Dear @CptPlastic,

What's your nextcloud version ? Database version ?

**Comment by CptPlastic** [comment]
NC = 23.0.4

**Comment by baimard** [comment]
Can I create an account on your instance?

**Comment by baimard** [comment]
I need more information please.
