### ISSUE TITLE
l10n: Understanding issue of "Special Drawing Rights"

### ISSUE THREAD

**Issue by rakekniven** [baimard/gestion#239]
https://github.com/baimard/gestion/blob/80d953b8dd2717415f661f230a685f541f16252e/src/js/modules/list.mjs#L145

Please provide some context.

**Comment by rakekniven** [comment]
Is it related to here https://en.wikipedia.org/wiki/Special_drawing_rights ?

**Comment by baimard** [comment]
No it's base on ISO 4217 like you ask me.
https://fr.iban.com/currency-codes

![image](https://user-images.githubusercontent.com/7591697/165735897-808bfc7a-aa3c-4e28-9329-2e249c0cf6d7.png)

**Comment by rakekniven** [comment]
Yes, found it there as well on english page https://www.iban.com/currency-codes

I am not familar with many currencies.

**Comment by baimard** [comment]
Me too, I copied and pasted a wild list, so maybe there are some mistakes. Thank you for reporting !
