### ISSUE TITLE
[FR] Erreur à l'ajout d'un nouveau produit dans un devis

### ISSUE THREAD

**Issue by timkrief** [baimard/gestion#24]
Lorque l'on ajoute un produit dans un devis et qu'aucun produit n'existe, on devrait être redirigé vers la création d'un produit ou avoir une erreur claire. Erreur actuelle: 
![image](https://user-images.githubusercontent.com/14089949/137531857-96b6c22c-cba5-4208-bcbd-3c1923458255.png)

**Comment by baimard** [comment]
TODO
