### ISSUE TITLE
[EN] l10n: Company management

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#241]
Is Gestion a company?
[# Gestion company management](https://github.com/baimard/gestion/blob/9679ddcf4f7b92543c310a7e7ae6c87742b01b7f/appinfo/info.xml#L7)

Shouldn't there be, for example: `Gestion - company management` or `Company management by Gestion`.

**Comment by baimard** [comment]
Gestion is the name of the application. You could choice version you prefere

**Comment by rakekniven** [comment]
@baimard Please choose one of the suggestions and improve source string. Thank you.

**Comment by rakekniven** [comment]
Missed that one, sorry.
Have a nice weekend.
