### ISSUE TITLE
Error when using the button Send by Email.

### ISSUE THREAD

**Issue by bootlegyaga** [baimard/gestion#247]
Hello Developers, I recently installed the app Gestion to try and get good looking invoices to clients but was stopped at the final step when trying to send out the invoice via the button "Send by email" when I click into one of the invoices I want to send out.

The error message I am getting is "Is your global mail server configured in Nextcloud?". 

I already checked my configuration and verified it works, it passed the send test in the config menu, and it can send emails with the Appointment app. 

Our Nextcloud version is 24.0.0.

Thank you!

**Comment by baimard** [comment]
Do you have a more explicit log in Developper tools ? (section : network)

**Comment by bootlegyaga** [comment]
Hello, good Monday to you!
I don't know where Developer Tools is but I found this error message in the Logging tools
[PHP] Error: Error: Undefined variable $mailer at /var/www/nextcloud/apps/gestion/lib/Settings/GestionAdmin.php#30 at <<closure>>

 0. /var/www/nextcloud/apps/gestion/lib/Settings/GestionAdmin.php line 30
    OC\Log\ErrorHandler::onError()
 1. <<closure>>
    OCA\Gestion\Settings\GestionAdmin->__construct()
 2. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 108
    ReflectionClass->newInstanceArgs()
 3. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 116
    OC\AppFramework\Utility\SimpleContainer->buildClass()
 4. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 133
    OC\AppFramework\Utility\SimpleContainer->resolve()
 5. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 465
    OC\AppFramework\Utility\SimpleContainer->query()
 6. /var/www/nextcloud/lib/private/ServerContainer.php line 145
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
 7. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 57
    OC\ServerContainer->query()
 8. /var/www/nextcloud/lib/private/Settings/Manager.php line 194
    OC\AppFramework\Utility\SimpleContainer->get()
 9. /var/www/nextcloud/lib/private/Settings/Manager.php line 339
    OC\Settings\Manager->getSettings()
10. /var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 82
    OC\Settings\Manager->getAllowedAdminSettings()
11. /var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 115
    OCA\Settings\Controller\AdminSettingsController->formatSections()
12. /var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 67
    OCA\Settings\Controller\AdminSettingsController->formatAdminSections()
13. /var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 139
    OCA\Settings\Controller\AdminSettingsController->getNavigationParameters()
14. /var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php line 68
    OCA\Settings\Controller\AdminSettingsController->getIndexResponse()
15. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AdminSettingsController->index()
16. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
17. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
18. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
19. /var/www/nextcloud/lib/base.php line 1023
    OC\Route\Router->match()
20. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

GET /index.php/settings/admin/logging
from 10.0.1.167 by sandbox-admin at 2022-06-27T17:18:49+02:00

**Comment by baimard** [comment]
Good monday too !

I will have a look this week :)

**Comment by baimard** [comment]
I took a look on this bug. But everythings working well in nextcloud 24.0.0

What's your php version ? Database version ? etc ?

**Comment by bootlegyaga** [comment]
Hello there!
Sorry for the late response, let me list out everything I know
PHP:  Version: 8.0.15
Database: MySQL 10.5.5
Gestion: 2.1.1

Nothing has changed since the last time.

**Comment by baimard** [comment]
Is your https://your.tld/settings/admin config for mail ?

**Comment by bootlegyaga** [comment]
Yeah the mail is setup, it sends mail with other apps.

**Comment by baimard** [comment]
I think I have find the problem.
Do you have access to the source code of gestion app ?

**Comment by bootlegyaga** [comment]
I do have access to the source code to edit yes.

**Comment by baimard** [comment]
in /var/www/nextcloud/apps/gestion/lib/Settings/GestionAdmin.php

Could you remove this line #30 :
```
        $this->mailer = $mailer;

**Comment by bootlegyaga** [comment]
I deleted the line and tested it still doesn't work but doesn't show up in logs either. There is an error message when I click send "Is your global mail server configured in Nextcloud?" I verified by sending an email from the cloud and it sent.

**Comment by baimard** [comment]
Could you show me your nextcloud config file ? (be carefull of your private data (password etc..))

**Comment by bootlegyaga** [comment]
```
<?php
$CONFIG = array (
  'passwordsalt' => '*****',
  'secret' => '****',
  'trusted_domains' => 
  array (
    0 => '***.private-cloud.biz',
    1 => 'localhost',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '24.0.0.12',
  'overwrite.cli.url' => 'https://***.private-cloud.biz',
  'dbname' => 'nc_***',
  'dbhost' => 'database:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nc_***',
  'dbpassword' => '***',
  'installed' => true,
  'instanceid' => '***',
  'trusted_proxies' => 
  array (
    0 => 'nginx',
    1 => 'localhost',
  ),
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => '***',
  ),
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'loglevel' => 0,
  'logtimezone' => '***',
  'cron_log' => 'true',
  'log_rotate_size' => '***',
  'updater.release.channel' => 'beta',
  'default_language' => 'en',
  'default_locale' => 'en_CA',
  'app_install_overwrite' => 
  array (
    0 => 'files_external_gdrive',
    1 => 'ehr',
    2 => 'data_request',
    3 => 'polls',
    4 => 'bbb',
    5 => 'socialsharing_twitter',
    6 => 'appointments',
    7 => 'health',
    8 => 'admin_notifications',
    9 => 'pdfdraw',
    10 => 'apporder',
    11 => 'workflow_pdf_converter',
    12 => 'drawio',
    13 => 'event_update_notification',
    14 => 'onlyoffice',
    15 => 'ransomware_protection',
    16 => 'talk_matterbridge',
    17 => 'talked',
    18 => 'timemanager',
    19 => 'integration_whiteboard',
    20 => 'workflow_script',
    21 => 'bruteforcesettings',
    22 => 'breezedark',
    23 => 'side_menu',
    24 => 'files_mindmap',
    25 => 'gestion',
    26 => 'riotchat',
    27 => 'registration',
    28 => 'integration_restya',
    29 => 'podcast',
    30 => 'files_reader',
    31 => 'social',
    32 => 'shifts',
  ),
  'mail_from_address' => 'support',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '***',
  'mail_smtphost' => 'mail.***.ca',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'support@***.ca',
  'mail_smtppassword' => '***',
  'maintenance' => false,
  'theme' => '',
  'simpleSignUpLink.shown' => false,
  'knowledgebaseenabled' => false,
  'mail_smtpauthtype' => 'LOGIN',
);

```

**Comment by bootlegyaga** [comment]
Good morning! I went through the config.php file and took out some private info hopefully didn't take out anything important.

**Comment by baimard** [comment]
> Good morning! I went through the config.php file and took out some private info hopefully didn't take out anything important.

looks ok, I'm gone investigating again. thank you !

**Comment by bootlegyaga** [comment]
Thank you so much!

**Comment by baimard** [comment]
Here is mine ... no difference ... 
```
  'mail_from_address' => 'nextcloud',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'cybercorp.fr',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '*.cybercorp.fr',
  'mail_smtpport' => '*',
  'mail_smtpname' => 'nextcloud@cybercorp.fr',
  'mail_smtppassword' => '*',
```

**Comment by baimard** [comment]
Nextstep, could you update your Nextcloud ?

**Comment by baimard** [comment]
And next next step, could you add me an account on your Nextcloud ?

**Comment by bootlegyaga** [comment]
I will have to address that with my boss to see if it's possible, I will get back to you asap

**Comment by bootlegyaga** [comment]
I sent you an email to benjamin@cybercorp.fr regarding the logins for the cloud.

**Comment by baimard** [comment]
Ok the problem now is : 

![Capture d’écran du 2022-07-22 20-59-05](https://user-images.githubusercontent.com/7591697/180505972-13b5dd9d-ef73-480f-8583-f2b81bd45544.png)

![Capture d’écran du 2022-07-22 20-59-01](https://user-images.githubusercontent.com/7591697/180505975-9cd22582-7bce-4f16-a8b9-cd0ab30f756e.png)

you need to configure your apache or nginx ! tell me if that solve your problem

https://blog.hubspot.com/website/413-request-entity-too-large#:~:text=What%20does%20%E2%80%9C413%20Request%20Entity,error%20to%20alert%20the%20client.

**Comment by bootlegyaga** [comment]
I changed the nginx config to allow 1000M through, restarted nginx and it still can't send (giving the error 413 still)

**Comment by baimard** [comment]
Also need apache2

**Comment by baimard** [comment]
Any news ?

**Comment by bootlegyaga** [comment]
Sorry for not being able to post any update but I've been waiting for the apache server access to modify but nothing yet

**Comment by baimard** [comment]
Dear, do you have some news ?
