### ISSUE TITLE
i have this error with gestion app

### ISSUE THREAD

**Issue by viaocc** [baimard/gestion#248]
Error interno del servidor
El servidor no ha podido completar tu petición.

Si sucede de nuevo, por favor, envía los detalles técnicos a continuación al administrador del servidor.

Pueden verse más detalles en el registro del servidor.

Detalles técnicos
Dirección remota: 190.234.181.70
ID de la solicitud: jA6N0mz58zwT43NEchar

**Comment by baimard** [comment]
Ola,

Engles por favor :)

**Comment by viaocc** [comment]
Hi, i am from Peru  This says the aplication when i try to run on nextcloud  Gestion - By Benjamin AIMARD licensed under AGPL  Internal Server ErrorThe server was unable to complete your request. If it happens again, please send the technical details below to the server administrator. More details can be seen in the server log. Remote address: 190.234.181.70Request ID: jA6N0mz58zwT43NEchar     Sent from Mail for Windows From: BenjaminSent: miércoles, 29 de junio de 2022 01:48To: baimard/gestionCc: viaocc; AuthorSubject: Re: [baimard/gestion] i have this error with gestion app (Issue #248) Ola,Engles por favor :)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
