### ISSUE TITLE
Configuration option

### ISSUE THREAD

**Issue by Khathijasafana** [baimard/gestion#250]
In the configuration option , I cannot EDIT 

**Company legal information line one**
This is the first line in the footer of your Quote/Invoice with all legal information you need.

At first I could edit . Then I deleted the content from that field. After that its not working.

Can anyone help with this query

**Comment by baimard** [comment]
Refresh and "-" could be appear.

**Comment by Khathijasafana** [comment]
Thank you for your response :-)

<img width="250" alt="Screenshot 2022-07-06 182506" src="https://user-images.githubusercontent.com/93784439/177573509-cbac270e-a8c2-49d3-b5e8-0060fb724790.png">


I couldn't find the "-" symbol to edit the option . Please check the attached image

**Comment by baimard** [comment]
Maybe a bug Let me take a look.

**Comment by Khathijasafana** [comment]
Sure. Thanks

**Comment by baimard** [comment]
Ok, I find the bug, it's when you press "enter" for validation without text.

"enter" create a return case at the end of the text. that cause the "-" doesn't appear ...

I need to correct that.

[Kazam_screencast_00002.webm](https://user-images.githubusercontent.com/7591697/177692797-546396b2-dc21-42d5-b9e0-c1b5965a13da.webm)

**Comment by Khathijasafana** [comment]
Hi @baimard ,

Yes ,I can see it is reflecting in the video that is shared. However when I tried , its still the same.

<img width="220" alt="Screenshot 2022-07-14 100619" src="https://user-images.githubusercontent.com/93784439/178911907-32b9fdb0-6a62-458b-9450-483b57442038.png">

**Comment by Khathijasafana** [comment]
Hi @baimard ,

Can you please check the snapshot shared. Text Cursor is still not reflecting in my environment.

<img width="140" alt="Screenshot 2022-07-17 102004" src="https://user-images.githubusercontent.com/93784439/179386604-6689320a-e4ec-4f8f-b27d-678a921d873e.png">



Thank you in advance

**Comment by baimard** [comment]
Yes you can change directly in database to recover the value pending fix

**Comment by baimard** [comment]
I made modification in the version 2.1.3, available soon.

Don't forget, If your like my work :

    Buy me a coffee and share a message : https://www.buymeacoffee.com/benjaminaimard
    Share my project
    Leave me a comment : https://apps.nextcloud.com/apps/gestion

thank you for support !

**Comment by Khathijasafana** [comment]
Thank you for your support
