### ISSUE TITLE
When invoice is generated in gestion , how to edit comment option?

### ISSUE THREAD

**Issue by Khathijasafana** [baimard/gestion#251]
Hi all,

When invoice is generated in gestion , how to edit comment option?

<img width="752" alt="Screenshot 2022-07-04 172209" src="https://user-images.githubusercontent.com/93784439/177163608-6abbd6e2-ab20-47d2-bf1b-6534880fcc2a.png">

Can anyone please help on this query

**Comment by Khathijasafana** [comment]
> You can edit the comment in quote.:) ⁣cordialement, Benjamin AIMARD​Le 4 juil. 2022 à 15:23, à 15:23, Khathijasafana ***@***.***> a écrit:
> […](#)
> Hi all, When invoice is generated in gestion , how to edit comment option? <img width="752" alt="Screenshot 2022-07-04 172209" src="https://user-images.githubusercontent.com/93784439/177163608-6abbd6e2-ab20-47d2-bf1b-6534880fcc2a.png"> Can anyone please help on this query -- Reply to this email directly or view it on GitHub: #251 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>



<img width="755" alt="Screenshot 2022-07-04 212822" src="https://user-images.githubusercontent.com/93784439/177198445-0a175d1d-8281-47bf-aac3-f8ffebb9bb23.png">

Thanks for your reply. Can you please let me know where to edit the comment option in Quotes?

**Comment by baimard** [comment]
In quote section just click on "-" below "Comment" that can do the trick ?

**Comment by Khathijasafana** [comment]
Much appreciate your response, @baimard . This is working. Need to click on comment in Quote option .
