### ISSUE TITLE
Please grant nextcloud-bot admin permissions

### ISSUE THREAD

**Issue by nickvergessen** [baimard/gestion#253]
Since 4 days the translation syncing is not working anymore as the master branch is protected and the bot is not an admin, so it can no long push the new translations:

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:baimard/gestion
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to '[git@github.com:baimard/gestion](mailto:git@github.com:baimard/gestion)'
```

**Comment by nickvergessen** [comment]
Ah, it's because it's a personal repository and not one from an organisation. Then you need to disable the branch protection IIRC

**Comment by baimard** [comment]
Done tell me if it's ok, and sorry.

**Comment by nickvergessen** [comment]
https://github.com/baimard/gestion/commit/dbb500eb75f4b78ff4a76670d9a27cf9665aec16

Worked again.
No worries, it's not the first time and will not be the last time this happens 😅👍
