### ISSUE TITLE
Screenshots in the appstore are broken

### ISSUE THREAD

**Issue by come-nc** [baimard/gestion#263]
Hello,

The screenshot in master branch which are used for the appstore are broken for most of them (screens of a blank firstrunwizard):
https://github.com/baimard/gestion/tree/master/tests/Unit/Panther/screens

See https://apps.nextcloud.com/apps/gestion

**Comment by baimard** [comment]
Thank you for repporting !

**Comment by baimard** [comment]
If you love my work don't forget to https://www.buymeacoffee.com/benjaminaimard
