### ISSUE TITLE
Unable to enable Gestion app after upgrade

### ISSUE THREAD

**Issue by Mageti** [baimard/gestion#264]
**Describe the bug**
I tried to update the gestion app on my nextcloud, but encountered en error. I disabled it, and when I try to enable it back, I get this error :
```
www-data@ced8a4d15f92:~/html$ ./occ app:enable gestion
Database error when running migration 20101Date20220722194447 for app gestion
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
www-data@ced8a4d15f92:~/html$
```

**To Reproduce**
I do not know how to reproduce, sorry

**Expected behavior**
App should be upgraded or enabled back without error

If I can help you by providing SQL content for debugging, please give me the SQL commands and I happily execute them.

**Comment by baimard** [comment]
Could you please remove the file under 
```
gestion/lib/Migration/Version20104Date20220728143910.php
```
tell me if that correct the bug :)

**Comment by Mageti** [comment]
Nothing, sorry :
```www-data@ced8a4d15f92:~/html$ rm custom_apps/gestion/lib/Migration/Version20104Date20220728143910.php
www-data@ced8a4d15f92:~/html$ ./occ app:enable gestion
Database error when running migration 20101Date20220722194447 for app gestion
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
```

**Comment by Mageti** [comment]
But removing `gestion/lib/Migration/Version20101Date20220722194447.php` did the trick

**Comment by baimard** [comment]
sorry for that, it's my mistake first ! I will correct that. Thank you for repporting :)

**Comment by Mageti** [comment]
Great, thank you !
