### ISSUE TITLE
logo at invoices,.. does not work properly

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [baimard/gestion#271]
I use gestion version 2.1.6
Nextcloud Version: 24.0.4

MY problem:

I located the logo.png in the gestion folder (was not existing, so I have created it).
It does not work.
Also if I just put it into the root folder of my files app it does not work.

There is no erros in the logs, it just tells me after locating it still the hint that I should locate it into the gestion folder in my files app.

**Comment by baimard** [comment]
Maybe cache ?

**Comment by MrLoverLoverMMMM** [comment]
no, that was not the issue.
its not loaded at the network shell even at refresh with clear cache.

**Comment by baimard** [comment]
Have you create "gestion" or ".gestion" folder ?

**Comment by MrLoverLoverMMMM** [comment]
That was the issue , thanks :)
I made gestion not .gestion.
My bad
Issue can be closed :)

**Comment by baimard** [comment]
No problem, I'm happy to help.

If you love my work don't forget to https://www.buymeacoffee.com/benjaminaimard

❤️
