### ISSUE TITLE
Cannot Delete Testbills

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [baimard/gestion#281]
Hello!
I created testproducts, offers and bills.
All of those elements where deleteable, but I wheren't able to delete the testbill from the system.
This is also occuring still with update: 2.1.7

best regards

Patrick

**Comment by baimard** [comment]
Thank you it's taken into account

**Comment by baimard** [comment]
@MrLoverLoverMMMM from the bottom the fourth option, is disable ou enable ?

**Comment by MrLoverLoverMMMM** [comment]
non of both??
![image](https://user-images.githubusercontent.com/17781278/187154677-58cd2c71-c64e-4727-91ac-6ef71296d2df.png)

**Comment by baimard** [comment]
configuration section.

**Comment by MrLoverLoverMMMM** [comment]
also nope, sadly ;)

![image](https://user-images.githubusercontent.com/17781278/187157262-9dc66980-c244-43a0-8ee5-64332a1ea6b1.png)


![image](https://user-images.githubusercontent.com/17781278/187157402-a795f54e-2963-4e54-8a4b-3bebc270b97c.png)

**Comment by baimard** [comment]
https://github.com/baimard/gestion/blob/master/tests/Unit/Panther/screens/config.png

**Comment by baimard** [comment]
"Meine Firma" click her

**Comment by MrLoverLoverMMMM** [comment]
![image](https://user-images.githubusercontent.com/17781278/187157579-bce1a2be-132b-4128-bdcd-024c982ea3f7.png)

**Comment by baimard** [comment]
I don't speak germain, but Aktivieren, means Enable ?

**Comment by MrLoverLoverMMMM** [comment]
yes
I have only 2 options there
enable or disable

**Comment by baimard** [comment]
Ok, Enable means you can't delete bill, because in some countries, you need to have bill consecutive and not interrupt.

If you wan't to delete a bill, you need to disable this option :)

**Comment by MrLoverLoverMMMM** [comment]
ok, but why the hint says: "Activate this if you want to enable automatic bill number generation" if its about deletion?

**Comment by MrLoverLoverMMMM** [comment]
An additional hint "activate this to delete bills" would be nice ;)

**Comment by baimard** [comment]
Hint can be improve you're write.

Activate mean: can't delete and automatic bill number generated.
Disable mean: can delete and manual bill name.

**Comment by baimard** [comment]
this is good for you ?

**Comment by MrLoverLoverMMMM** [comment]
Activate mean: can't delete and automatic bill number generated.
Disable mean: can delete and manual bill name.

==> Then the german translation is wrong.
Please overwork the hint, then all is fine :)

**Comment by baimard** [comment]
@rakekniven do you have information about that ?

**Comment by MrLoverLoverMMMM** [comment]
it says option 293 at my setup.
I think that it does not say that it should be deactivated for bill deletion

**Comment by baimard** [comment]
Attention, in fact if you start with this option enable, you shouldn't deactivate it. Because you could corrupt the numbering sequence for invoice.

I don't know in Germany but in France all your invoice numbers must follow each other

**Comment by MrLoverLoverMMMM** [comment]
OK
In this case its really mandatory that its possible to delete bills without corrupting the systems, if possible.
best regards

**Comment by baimard** [comment]
It's complicated, because technically it's possible. But if I respect the law I can't ...

**Comment by MrLoverLoverMMMM** [comment]
Hm..
What about making a drop down where you can choose your country.
Or an option: allow bill deletion (attention: might not be allowed in some countries, use at own risk)??

**Comment by MrLoverLoverMMMM** [comment]
I am sure that I am not the only one who wants to first just test the system a bit with demo bills before using it or?
for that at least should be some way

**Comment by baimard** [comment]
> I am sure that I am not the only one who wants to first just test the system a bit with demo bills before using it or?
> for that at least should be some way

You're not the only one for sur. It's why I create this mode.

Gestion isn't perfect :)

But thank you for this conversation.

**Comment by MrLoverLoverMMMM** [comment]
OK :)
Thank you very much :)
So whats the best way that I can delete my demo bill and reactivate the auto number?

**Comment by baimard** [comment]
For me the best way is to reuse for an other customer the invoice number

**Comment by MrLoverLoverMMMM** [comment]
I have an idea.
What about making a reset to delivery button.
Or button delete all, which wipes the whole gestion?

May problem. I have delete the bill now and reactivated the auto number, as my tests are done.
How can I now make sure nothing bad is happening?

**Comment by baimard** [comment]
the problem is that your database have increment ID ..., I need to develop a reset function as you say.

v2.1.8

**Comment by MrLoverLoverMMMM** [comment]
Thank you very much :)
That would be awesome :)

**Comment by baimard** [comment]
:) that was in my mind.

**Comment by MrLoverLoverMMMM** [comment]
why is this thread closed if its not resolved?

**Comment by baimard** [comment]
In fact, when an invoice is created you just cannot remove it ... I need 
to improve this part by a button to lock invoice when it's send to 
customer for example.

---
Cordialement,
Benjamin AIMARD

Le 2023-03-06 10:41, MrLoverLoverMMMM a écrit :

> why is this thread closed if its not resolved?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you modified the open/close 
> state.Message ID: ***@***.***>


Links:
------
[1] 
https://github.com/baimard/gestion/issues/281#issuecomment-1455891562
[2]

**Comment by MrLoverLoverMMMM** [comment]
+ The Drop/Down to deactivate automatic bill numbers is not avialable anymore.
Is there a manual way how to resett the app for 1 certain user?
