### ISSUE TITLE
Generating invoice fails because javascript is detected as disabled

### ISSUE THREAD

**Issue by infra-monkey** [baimard/gestion#282]
**Describe the bug**
When clicking on "Add invoice" I receive a Internal error saying that javascript is not enabled in Firefox. However when checking in "about:config" it is set to enabled.
On Brave, the issue did not occur.

Note: When opening in brave, I saw that 2 empty invoices where created matching the 2 failed attempts on Firefox.

**To Reproduce**
1. Go to 'Invoices'
2. Click on 'Add Invoice'

**Expected behavior**
The Invoice should be create.
In case of error, the empty invoice should not have been created to avoid pollution

**Screenshots**
![Screenshot_20220830_105317](https://user-images.githubusercontent.com/43171889/187394835-d4278416-a5f0-43ae-8bca-2b8bbf63f823.png)

**Desktop (please complete the following information):**
 - OS: Linux Fedora 36 - KDE Plasma Wayland
 - Browser: Firefox 104.0
 - Version: Gestion 2.1.6 and 2.1.7

**Additional context**
I also created a brand new test user to be sure it is not linked to some bad cached data.

**Comment by baimard** [comment]
Maybe a module which disable javascript ? it's not app issue, but it's due to your configuration.
