### ISSUE TITLE
logo at invoices gestion version 2.1.7 Nextcloud Version: 24.0.5 12.09.22

### ISSUE THREAD

**Issue by svenweida** [baimard/gestion#284]
**Describe the bug**
If folder ".gestion" is created with document "logo.png" the implementation in the invoice template does not take place.

**To Reproduce**
1. Go to 'Gestion'
2. Click on 'Bill'
3. Open the Bill where you can see the Template 'there is still the Note how you can implement the Logo'
4. Download the PDF 'the isn't a Logo
5. If there is no Folder ".gestion"  in the app folder "/httpdocs/apps/gestion". I created one with the logo

**Expected behavior**

**Desktop (please complete the following information):**
 - MACOS
 - Browser [I tryed on Chrome and Firefox]

**Additional context**
The Descripiton is not clear, those the ".gestion" Folder should be in "/httpdocs/apps/gestion" or "/httpdocs/apps/files"

**Comment by svenweida** [comment]
Problem solved: [#270](https://github.com/baimard/gestion/discussions/270#discussion-4309950)

**Comment by baimard** [comment]
Good reading :) I close wish you the best
