### ISSUE TITLE
bad display and malfunction when starting the app in nextcloud 22

### ISSUE THREAD

**Issue by Josuate** [baimard/gestion#285]
bad display and malfunction when starting the app in nextcloud 22 server on safari ios, chrome windows 

![image](https://user-images.githubusercontent.com/111056539/192204306-b4c8b2f8-8e11-4707-9c6f-e09358ef8cfb.png)

**Comment by baimard** [comment]
Hello, looks like javascript is block in your instance. Could you please open developper tools and show errors ?

**Comment by Josuate** [comment]
good day, I am attaching the log:
ValueError: The arguments array must contain 1 items, 0 given
/snap/nextcloud/28713/htdocs/lib/private/L10N/L10NString.php - line 82:

vsprintf()

/snap/nextcloud/28713/htdocs/lib/private/L10N/L10N.php - line 106:

OC\L10N\L10NString->__toString()

/snap/nextcloud/28713/htdocs/lib/private/L10N/LazyL10N.php - line 52:

OC\L10N\L10N->t()

/var/snap/nextcloud/28713/nextcloud/extra-apps/gestion/templates/content/changelog.php - line 43:

OC\L10N\LazyL10N->t()

/snap/nextcloud/28713/htdocs/lib/private/Template/Base.php - line 180:

include("/var/snap/n ... p")

/snap/nextcloud/28713/htdocs/lib/private/legacy/OC_Template.php - line 227:

OC\Template\Base->load()

/var/snap/nextcloud/28713/nextcloud/extra-apps/gestion/templates/index.php - line 14:

OC_Template->inc()

/snap/nextcloud/28713/htdocs/lib/private/Template/Base.php - line 180:

include("/var/snap/n ... p")

/snap/nextcloud/28713/htdocs/lib/private/Template/Base.php - line 150:

OC\Template\Base->load()

/snap/nextcloud/28713/htdocs/lib/private/legacy/OC_Template.php - line 179:

OC\Template\Base->fetchPage()

/snap/nextcloud/28713/htdocs/lib/public/AppFramework/Http/TemplateResponse.php - line 204:

OC_Template->fetchPage()

/snap/nextcloud/28713/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 171:

OCP\AppFramework\Http\TemplateResponse->render()

/snap/nextcloud/28713/htdocs/lib/private/AppFramework/App.php - line 156:

OC\AppFramework\Http\Dispatcher->dispatch()

/snap/nextcloud/28713/htdocs/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/snap/nextcloud/28713/htdocs/lib/base.php - line 1006:

OC\Route\Router->match()

/snap/nextcloud/28713/htdocs/index.php - line 36:

OC::handleRequest()

**Comment by Josuate** [comment]
![image](https://user-images.githubusercontent.com/111056539/192451658-de1976d0-9130-4d55-b19d-59e26d5f6dc4.png)

**Comment by baimard** [comment]
An other question, why are you in NC 22 ? is it possible for you to update ?

**Comment by Josuate** [comment]
we still have all the servers on NC 22 and everything runs there even for this application, according to the apps store it is compatible. can we drive it on this NC version as well?

**Comment by baimard** [comment]
I need to test

**Comment by Josuate** [comment]
yes i need to test

**Comment by Josuate** [comment]
can we make it functional also on the NC 22 version?

**Comment by baimard** [comment]
i will try

**Comment by Josuate** [comment]
thanks it would help us a lot

**Comment by baimard** [comment]
Your welcome, if you're a company don't forget to support the project :)

**Comment by Josuate** [comment]
yes, we are a company, we will support the project, but since it does not work for us on the NC 22 version, it is difficult to support it if we cannot test the functionality, and we would also contribute with improvements and finances for the future

**Comment by Josuate** [comment]
Can you really give me instructions on how to start the application on NC22 or where to enable and set it?

**Comment by baimard** [comment]
You have a bug with the translation tools, it's internal to NC. I need to test with NC22 in the next days what happend and if it's necessary release the app.

Just wait please :)

**Comment by Josuate** [comment]
ok thank you and I will wait for the test result

**Comment by Josuate** [comment]
good day, did you manage to find out what the problem is?

**Comment by Josuate** [comment]
good day, I updated nextcloud to version 24 and I still have the same problem with the application and the same voice

**Comment by baimard** [comment]
You have a problem in your configuration, could you please provide me an account to your nextcloud instance ?

**Comment by Josuate** [comment]
here is the ip http://194.182.82.136/index.php/
user: Tuho
pass: Janci2022.

**Comment by Josuate** [comment]
Hello

**Comment by Josuate** [comment]
Hello where is problem in guestion

**Comment by baimard** [comment]
Please wait

**Comment by Josuate** [comment]
Connect on my nextcloud is OK

**Comment by baimard** [comment]
![Capture d’écran du 2022-10-02 20-59-15](https://user-images.githubusercontent.com/7591697/193471360-6a9e61de-94cb-402c-a46f-a9c47e0f53b2.png)

It's a L10N problem, I need to investigate more, I turned your instance in english that temporaly solve the problem

**Comment by Josuate** [comment]
i need in slovak lenguage

**Comment by baimard** [comment]
It's a big bug, I need time to solved.

**Comment by Josuate** [comment]
good day, I want to ask if you have any new information regarding this problem?

**Comment by Josuate** [comment]
good day, I want to ask if we already have a solution, we would need to test it for our client

**Comment by baimard** [comment]
are you on nc 22 anymore ?

**Comment by Josuate** [comment]
I already use NC24 everywhere and it still doesn't work for us, the same error

Dňa 22. 10. 2022 o 10:34, Benjamin ***@***.******@***.***>> napísal:

are you on nc 22 anymore ?

**Comment by baimard** [comment]
Could you tell me credential again by mail on your instance ? contact@cybercorp.fr
