### ISSUE TITLE
Nextcloud 25

### ISSUE THREAD

**Issue by bantanamera** [baimard/gestion#291]
When will there be a version for Nextcloud 25? 
I can install the untested app, but nothing happens when I will set up my own data.
I am using NC 25.0.0 RC3
maybe I'm just a little early?

**Comment by baimard** [comment]
You are very earlier Ahah, do you want to be a beta tester fort NC 25 ?

**Comment by bantanamera** [comment]
Yes, I hope it's not too complicated

**Comment by bantanamera** [comment]
the same behavior, if I want to set up the company, nothing else happens.

**Comment by baimard** [comment]
do you have an error message in console ? (F12)

**Comment by bantanamera** [comment]
GET https://xxxxxxx.xxxx/apps/gestion/js/820.app.js?v=33a51f7b-354 net::ERR_ABORTED 404
config:1 Refused to execute script from 'https://xxxxxxx.xxxx/apps/gestion/js/820.app.js?v=33a51f7b-354' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by baimard** [comment]
Ok, I find the bug, it's not due to the error. there are 2 problems : 
- Error on script 820 that doesn't exist
- Error in CSS

Reduce your Window browser ... and see that everythings works

**Comment by bantanamera** [comment]
?  you have to be more precise, should I use a lower version of the browser?

**Comment by baimard** [comment]
No just reduce de size of Firefox or Chrome 😂

**Comment by bantanamera** [comment]
sorry..now i understand, the windows size has no change

**Comment by bantanamera** [comment]
now i figured it out, i reduced the window to 1024 pixels wide and then the window for editing the company data appears

**Comment by baimard** [comment]
this bug kill me ....

**Comment by baimard** [comment]
fix in 2.2.2, let me see if it's okey ?

**Comment by bantanamera** [comment]
hi, now its fine!
