### ISSUE TITLE
collaborative management?

### ISSUE THREAD

**Issue by yeupou** [baimard/gestion#297]
Hi, 

You app seems quite useful. However, it was not obvious to me the best way for several users to manage the same enterprise. That would make your software useful not only for micro-enterprise but also for very small companies.

Is there any plans about it?

Regards,

**Comment by baimard** [comment]
Dear,
Yes it's in my plan, please see this link https://github.com/baimard/gestion/discussions/198
and the roadmap https://github.com/baimard/gestion/discussions/127

This is not an issue, could you please speak on the discussions section :) ?

**Comment by yeupou** [comment]
Ha sure, sorry, I did not even notice this section!
