### ISSUE TITLE
billing templates

### ISSUE THREAD

**Issue by yeupou** [baimard/gestion#298]
Hi,

I would be convenient if we could set some templates, like for instance default billing name, instead of being:

FACTURE-N  (a bit redundant, "facture N° FACTURE-4") 

 but something like

quoteref-N  (so "facture N° 12c-4" for example)

**Comment by yeupou** [comment]
(in the same spirit, if would be convenient to set a default payment method for a given quote, so every relevant invoices is already set)

**Comment by baimard** [comment]
Tell if this version correct this bug

**Comment by baimard** [comment]
> It is possible to use "quoteref" (the quote reference name) as prefix? What is the syntax to be used, if so?

Yes it's possible but it's not a priority sorry /o\

> The custom prefix works. Though, if I completely remove the prefix, I still get the "-" in front of the number, so I guess "Facture n° -2" etc. The "-" should be part of the configurable part.
No, "-" appear if the option is empty. So just configure what you want.

**Comment by yeupou** [comment]
> Yes it's possible but it's not a priority sorry /o\

:-) No problem, just asking.

> No, "-" appear if the option is empty. So just configure what you want.

Ahem. So it is mandatory to have a prefix, we cannot have simple Facture n° 2 for instance? Ok, that is not a problem. 

Thanks for your attention.

**Comment by baimard** [comment]
> Ahem. So it is mandatory to have a prefix, we cannot have simple Facture n° 2 for instance? Ok, that is not a problem.

Je passe en français. Si tu veux "Facture n° N" Il faut écrire en prefix : "Facture n°"

Si tu veux juste que le numéro apparaisse, effectivement ça n'est pas possible. Je n'avais pas pensé à ce cas :)

**Comment by yeupou** [comment]
Si je mets en préfixe "Facture n°", le titre de la facture devient "Facture N° Facture n°-1".

Si je ne m'abuse, le titre est toujours : Facture N° $PREFIX-$NNNN

Du coup, si on met facture dans le préfixe, c'est un peu redondant. En ne mettant rien, on a toujours le tiret, mais ça ne doit pas être un cas de figure si fréquent. Si on veut quelque chose de minimaliste, F comme préfixe donc Facture n° F-1, ce qui me semble très correct.

**Comment by baimard** [comment]
J'ai compris ça y est ... je pense qu'il faut juste retirer le Facture n°, que je mette autre chose à la place ...

Bien vu !!!
