### ISSUE TITLE
not able to directly edit invoice name from the list

### ISSUE THREAD

**Issue by yeupou** [baimard/gestion#299]
In current version (2.2.2), the invoice name field is not editable directly from the list:

![image](https://user-images.githubusercontent.com/1160681/200279396-08d20d94-0548-4f19-926a-e0e4a4b11ef7.png)

**Comment by yeupou** [comment]
Ha, ok, right. 
Note that even with automatic invoice number set off, I was able to edit the invoice name within the full edition page. 

But I actually would like to use the automatic invoice number - with template as described in #298. :-)

**Comment by baimard** [comment]
So you need to wait :) for the other feature :). I'm alone on this project :'(

Thank you for your feedback

**Comment by yeupou** [comment]
Sure, no problem :-)   these are just suggestions. Thanks for the work done so far!

**Comment by baimard** [comment]
#313
