### ISSUE TITLE
feature request: variable VAT (per quotes)

### ISSUE THREAD

**Issue by yeupou** [baimard/gestion#300]
Hi,

In my uses cases, some invoices goes to different type of customers, some of them got VAT, some other none. 

Would it be possible to edit, at quote level, the VAT - for instance, setting it to 0 in a quote, so the tied invoices got 0% VAT?

Regards,

**Comment by yeupou** [comment]
Ok, checking the discussions, I noticed it was already requested https://github.com/baimard/gestion/discussions/202
In given example, though, it seems different VAT were pre-registered. It is probably easier to just add a database field for VAT in quote, pre-filled with the default, and make the VAT editable on the quote page.

**Comment by baimard** [comment]
In discussion #202
