### ISSUE TITLE
Gestion leaves empty `.pdf` file on export

### ISSUE THREAD

**Issue by normen** [baimard/gestion#303]
**Describe the bug**
When exporting a Quote to Nextcloud the process takes quite a while and after the file has been created there is also an empty `.pdf` file (no filename, only the extension) in the root folder of the cloud.

**To Reproduce**
1. Go to Gestion
2. Create a Quote
3. Export the Quote to NextCloud
4. Wait until theres feedback the file has been created
5. See empty `.pdf` file in cloud root folder

**Expected behavior**
The export should be immediate and there should be no file left in the cloud root folder.

**Screenshots**
<img width="850" alt="Bildschirmfoto 2022-11-13 um 15 43 47" src="https://user-images.githubusercontent.com/3270528/201527696-55276e3c-35e0-42f3-82a7-505218d59348.png">

**Desktop (please complete the following information):**
 - OS: iOS, MacOS
 - Browser Safari
 - Version 16

**Smartphone (please complete the following information):**
 - Device: iPhone/iPad/MacBook

**Additional context**

**Comment by baimard** [comment]
Hello, what's your nextcloud version ?

**Comment by normen** [comment]
24

**Comment by baimard** [comment]
Have you tried with another navigator ?

**Comment by normen** [comment]
Yes

**Comment by baimard** [comment]
have you an error in the developer tools ? "F12"

**Comment by normen** [comment]
The only relevant things seem to be this
```
[Debug] #1 – "0ms" – "Starting document clone with size 1152x453 scrolled to 0,0" (devisShow.app.js, line 2)
[Debug] #1 – "4900ms" – "Document cloned, element located at 308,-448 with size 840x975 using computed rendering" (devisShow.app.js, line 2)
[Debug] #1 – "4900ms" – "Starting DOM parsing" (devisShow.app.js, line 2)
[Debug] #1 – "4989ms" – "Added image data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAACrQAAAq0CAYAAAB7EgH4AAAABGdBTUEAALGPC/xhBQAACkFpQ0NQSUNDIFByb2ZpbGUAAEgNnZZ3VFPZF…" (devisShow.app.js, line 2)
"Added image data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAACrQAAAq0CAYAAAB7EgH4AAAABGdBTUEAALGPC/xhBQAACkFpQ0NQSUNDIFByb2ZpbGUAAEgNnZZ3VFPZFofPvTe90BIiICX0GnoJINI7SBUEUYlJgFAChoQmdkQFRhQRKVZkVMABR4ciY0UUC4OCYtcJ8hBQxsFRREXl3YxrCe+tNfPemv3HWd/Z57fX2Wfvfde6AFD8ggTCdFgBg"
[Debug] #1 – "5281ms" – "Starting renderer for element at 308,-448 with size 840x975" (devisShow.app.js, line 2)
[Debug] #1 – "5284ms" – "Canvas renderer initialized (840x975) with scale 2" (devisShow.app.js, line 2)
[Debug] #1 – "5794ms" – "Finished rendering" (devisShow.app.js, line 2)
[Error] TypeError: null is not an object (evaluating '$.source.postMessage')
	(anonyme Funktion) (content.js:2:182020)
```

**Comment by baimard** [comment]
Could you show me the quote ?

**Comment by normen** [comment]
Like so?
<img width="823" alt="Bildschirm­foto 2023-02-03 um 09 48 35" src="https://user-images.githubusercontent.com/3270528/216554208-98ae8c9f-9431-43b7-8d50-812294a48ab9.png">

**Comment by baimard** [comment]
Yes and the header if it's possible ? or on contact@cybercorp.fr

**Comment by baimard** [comment]
?

**Comment by jimbolaya** [comment]
If I could weigh in here. I'm having a similar issue. 

The first issue I encountere was that "post_max_size" in php.ini was not set to a large enough number. I got errors like:

`{"reqId":"ZeiAbcmqH9PTjkKNMX-16gAAAAg","level":3,"time":"2024-03-06T14:41:03+00:00","remoteAddr":"35.7.40.219","user":"jklaas","app":"PHP","method":"POST","url":"/index.php/apps/gestion/savePDF","message":"PHP Request Startup: POST Content-Length of 19063614 bytes exceeds the limit of 8388608 bytes at Unknown#0","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0","version":"26.0.12.2","data":{"app":"PHP"}}
`
until I changed it.

It creates a directory named after the quote. "Quote 1" in this case. 

If I take a look at the filesystem I get something like this:
`ls -l Quote\ 1/
total 0
-rw-r--r-- 1 www-data www-data 0 Mar  6 10:10 'INVOICE_'$'\n''_INVOICE--1_v1.0.pdf'
`
As you see, the file size is 0. I'm not sure why there's an escaped carriage return in the name. I've got "Show Hidden Files" checked in my options, but this does not show up in the Nextcloud Files interface.  Looking in the browser console, it sends 20MB in a POST, so in your nextcloud.log file. 

Here's what "SavePDF" shows in nextcloud.log when "post_max_size" is set to large enough.

`{"reqId":"ZeiHaRMNmMsbTOwcS__8NAAAAAQ","level":3,"time":"2024-03-06T15:10:56+00:00","remoteAddr":"35.7.40.219","user":"jklaas","app":"no app in context","method":"POST","url":"/index.php/apps/gestion/savePDF","message":"Exception thrown: OCP\\Files\\NotFoundException","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0","version":"26.0.12.2","exception":{"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Node/Node.php","line":363,"function":"getFileInfo","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Node.php","line":175,"function":"getMountPoint","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/nextcloud/apps/maps/lib/Hooks/FileHooks.php","line":191,"function":"getStorage","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/nextcloud/apps/maps/lib/Hooks/FileHooks.php","line":53,"function":"isUserNode","class":"OCA\\Maps\\Hooks\\FileHooks","type":"->"},{"function":"OCA\\Maps\\Hooks\\{closure}","class":"OCA\\Maps\\Hooks\\FileHooks","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Hooks/EmitterTrait.php","line":105,"function":"call_user_func_array"},{"file":"/var/www/nextcloud/lib/private/Hooks/PublicEmitter.php","line":40,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Root.php","line":144,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->"},{"function":"emit","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":73,"function":"call_user_func_array"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":101,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/HookConnector.php","line":117,"function":"emit","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":105,"function":"postWrite","class":"OC\\Files\\Node\\HookConnector","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1309,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1242,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":587,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":189,"function":"touch","class":"OC\\Files\\View","type":"->"},{"function":"newFile","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":73,"function":"call_user_func_array"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":427,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Controller/PageController.php","line":377,"function":"newFile","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"savePDF","class":"OCA\\Gestion\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1062,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Files/Node/Node.php","Line":114,"CustomMessage":"Exception thrown: OCP\\Files\\NotFoundException"}}`

I don't know if I'm interpreting this correctly, but it appears to be complaining about `Exception thrown: OCP\\Files\\NotFoundException` which may be from the escaped carriage return. in the name.

I copied the 20MB data from the browser console that was sent into a document (the paste still going on) and I'll see if that shows up as a PDF.

**Comment by jimbolaya** [comment]
I solved my issue. I never created a `logo.png` file. Once I created the logo.png file, the invoices printed.

Never the less, I would expect this to fail gracefully if there is no logo.png file. and not create a filename with a '\n' in the file name.
