### ISSUE TITLE
Is it possible to change Color of Footer information?

### ISSUE THREAD

**Issue by wp4711** [baimard/gestion#312]
By default, color of footer in quote (and bill) is light blue. 
Can I change it or is it possible to delete color and just let it white?

**Comment by baimard** [comment]
Yes it is. You can use the custom css plugins in nextcloud.

the flag are : .alert-info

**Comment by wp4711** [comment]
hmm, can you tell me what exactly i have to do?
tried to write following in custom css field:

.alert-info {
    color: #D3D3D3;
    background-color: #D3D3D3;
    border-color: #D3D3D3;
}

but that doesent work. color in quote is still light blue

**Comment by baimard** [comment]
Show me via printscreen exact place you want to change

**Comment by wp4711** [comment]
![grafik](https://user-images.githubusercontent.com/96334271/215111682-f1d80e98-9de3-45c2-945d-fc5a469c259f.png)

**Comment by wp4711** [comment]
this is also in pdf creation.
i would like to make that white only

**Comment by baimard** [comment]
I will investigate :)

**Comment by baimard** [comment]
Correct modification for custom css :)

.bootstrap-iso .alert {
  color: green !important;
  background-color: #fccfdc !important;
}

**Comment by baimard** [comment]
Don't forget, If your like my work :

Buy me a coffee and share a message : https://www.buymeacoffee.com/benjaminaimard
Share my project
Leave me a comment : https://apps.nextcloud.com/apps/gestion
thank you for support !
