### ISSUE TITLE
Error in migration script when updating Gestion to the latest version, 2.3.0

### ISSUE THREAD

**Issue by cedricbonhomme** [baimard/gestion#317]
**Describe the bug**
Error in migration script when updating Gestion to the latest version.

It's in the file `apps/gestion/lib/Migration/Version20203Date20230115010101.php`

**To Reproduce**

```bash
s$ php ./occ upgrade
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see https://www.php.net/manual/en/book.pcntl.php
Additionally the function 'pcntl_signal' and 'pcntl_signal_dispatch' need to be enabled in your php.ini.
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <gestion> ...
Exception: Database error when running migration 20203Date20230115010101 for app gestion
An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "user_id" of relation "oc_gestion_devis" contains null values
Update failed
Maintenance mode is kept active
Resetting log level
```

Latest version of Nextcloud, 25.0.4.

**Comment by Mageti** [comment]
Same here.  
I did that while waiting for the fix: 
```rm custom_apps/gestion/lib/Migration/Version20203Date20230115010101.php```

**Comment by baimard** [comment]
fresh install or upgrade ?

**Comment by baimard** [comment]
and database version mysql or postgresql ?

**Comment by Mageti** [comment]
upgrade on sqlite for me

**Comment by baimard** [comment]
I will make a new release this night

**Comment by Mageti** [comment]
Great, thank you very much :+1:

**Comment by cedricbonhomme** [comment]
Thank you !

**Comment by baimard** [comment]
Tell me if that fix !

**Comment by cedricbonhomme** [comment]
> Tell me if that fix !

This fix the issue for me ! Thank you very much !

**Comment by Mageti** [comment]
I confirm it's also good on my side.
Thank you very much !

**Comment by baimard** [comment]
Merci à vous pour la remonté du bug :)

Don't forget, If your like my work :

Buy me a coffee and share a message : https://www.buymeacoffee.com/benjaminaimard
Share my project
Leave me a comment : https://apps.nextcloud.com/apps/gestion
thank you for support !
