### ISSUE TITLE
erro with NC 25 

### ISSUE THREAD

**Issue by Josuate** [baimard/gestion#320]
good day, I still have a problem with Gestion and I have NC25
![Snip20230209_1](https://user-images.githubusercontent.com/111056539/217820589-3f088476-281d-443b-a9e9-4f8698e833d6.png)

**Comment by baimard** [comment]
I'm waiting for un accès to your nextcloud platform

**Comment by Josuate** [comment]
what do you need to access my nextcloud platform?

**Comment by baimard** [comment]
url and an account.

**Comment by Josuate** [comment]
url: https://cloud.e-organizer.eu/
login: benjamin
pass: 2023pass..

**Comment by baimard** [comment]
![image](https://user-images.githubusercontent.com/7591697/218173173-c7b3de51-b74b-4a8c-8358-928543ecb5d7.png)

**Comment by Josuate** [comment]
and you is this 
![Snip20230210_2](https://user-images.githubusercontent.com/111056539/218173766-b988fa51-e373-4dd6-a2ab-63769c143a9e.png)

**Comment by baimard** [comment]
langage please ?

Cordialement,
Benjamin AIMARD

Le 10/02/2023 à 19:51, Josuate a écrit :

**Comment by Josuate** [comment]
problem is slovak language, english is ok  can we translate it in Slovak?

**Comment by baimard** [comment]
https://github.com/nextcloud/nextcloud-l10n/issues/586

**Comment by baimard** [comment]
I find the bug, the nextrelease will correct the error

**Comment by baimard** [comment]
Tell me if the bug is corrected by version 2.3.3
