### ISSUE TITLE
[FR] Problème logo

### ISSUE THREAD

**Issue by LyonelB** [baimard/gestion#321]
**Describe the bug**
Le logo n'apparait pas.
J'ai créé un dossier ".gestion" dans "/apps/gestion" 
J'y ai ajouté mon logo.png mais j'ai du loupé quelque chose

**Comment by baimard** [comment]
Bonjour,
il ne faut pas créer le répertoire .gestion dans le répertoire /apps/gestion, mais dans le files du nextcloud. c'est à dire directement sur la page web dans les fichiers du cloud. aucune modification sur le serveur n'est nécessaire :)

**Comment by baimard** [comment]
Il doit déjà exister as tu affiché tes fichiers et dossiers cachés ?

**Comment by LyonelB** [comment]
Mille excuses ! 
Je n'avais pas coché pour l'affichage des dossiers cachés.
