### ISSUE TITLE
ID and Invoice number reset to 1 on generation

### ISSUE THREAD

**Issue by infra-monkey** [baimard/gestion#327]
**Describe the bug**
Invoice ID is reset to "1".
Since last update I guess, the Id when I create a quote or an invoice is at 1.

**To Reproduce**
1. Generate a new quote/invoice

**Expected behavior**
As the invoice title is also using an increment 

**Screenshots**
![image](https://user-images.githubusercontent.com/43171889/221832148-01aba88a-ffbb-4740-b051-42df16d471be.png)

**Desktop (please complete the following information):**
 - OS: Linux Fedora 37 , KDE 5.27.1 Wayland
 - Browser: firefox/brave
 - Version: 110.0/v1.48.171 

**Additional context**
 I am on a postgresql database with nextcloud in container.
By updating the database directly I can change the "Invoice number"  and "Id" to match what should be present. That way I can send an invoice with the correct sequence to my customer. 
Next invoice will also have a id = 1 

Is there a way to fix the system to have the correct ids on the next generation?

Db command to fix:
update oc_gestion_facture set num = 'INVOICE-12' where id = 29;
update oc_gestion_facture set user_id = 11 where id = 29;
update oc_gestion_devis set user_id = 11 where id = 14;

Note

**Comment by infra-monkey** [comment]
In the logs :
```
[PHP] Error: Error: Undefined array key "LAST_INSERT_ID" at /var/www/html/custom_apps/gestion/lib/Db/Bdd.php#280 at <<closure>>

0. /var/www/html/custom_apps/gestion/lib/Db/Bdd.php line 280
   OC\Log\ErrorHandler::onError(2, "Undefined array key \"LAST_INSERT_ID\"", "/var/www/html/c ... p", 280)
1. /var/www/html/custom_apps/gestion/lib/Db/Bdd.php line 124
   OCA\Gestion\Db\Bdd->lastinsertid("facture", "keycloak-18768b ... 6")
2. /var/www/html/custom_apps/gestion/lib/Controller/PageController.php line 279
   OCA\Gestion\Db\Bdd->insertFacture("keycloak-18768b ... 6")
3. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Gestion\Controller\PageController->insertFacture()
4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Gestion\Controller\PageController {}, "insertFacture")
5. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Gestion\Controller\PageController {}, "insertFacture")
6. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OCA\\Gestion\\C ... r", "insertFacture", OC\AppFramework\ ... {}, ["gestion.page.insertFacture"])
7. /var/www/html/lib/base.php line 1047
   OC\Route\Router->match("/apps/gestion/facture/insert")
8. /var/www/html/index.php line 36
   OC::handleRequest()

POST /index.phpion/facture/insert
from 192.168.3.51 by keycloak-18768b91-1cd3-4781-ada1-773119695616 at 2023-02-28T15:04:19+00:00
```

I have no idea how I got there :/ 
How to fix it?

**Comment by baimard** [comment]
/**
     * Get last insert id
     */
    public function lastinsertid($table,$idNextcloud){
        $sql = "SELECT max(user_id) as LAST_INSERT_ID FROM `" . $this->tableprefix . $table . "` WHERE " . $this->tableprefix . $table .".id_nextcloud = ?;";
        $res = $this->execSQLNoJsonReturn($sql,array($idNextcloud));
        return $res[0]['LAST_INSERT_ID'];
    }

Could you check this request directly in postgre ?

**Comment by baimard** [comment]
SELECT max(user_id) as LAST_INSERT_ID FROM `oc_gestion_facture` WHERE oc_gestion_facture.id_nextcloud = <YOURIDNEXTCLOUD>;

**Comment by infra-monkey** [comment]
```
# SELECT max(user_id) as LAST_INSERT_ID FROM oc_gestion_facture WHERE oc_gestion_facture.id_nextcloud = 'keycloak-18768b91-1cd3-4781-ada1-773119695616';
 last_insert_id 
----------------
             11
```
Looks good, I have only 11 entries.
Could it be trying for another id_nextcloud?

**Comment by infra-monkey** [comment]
And no worries, I know I'm not on a standard configuration, because I like to suffer apparently.
Which make me a good tester I guess :smile:

**Comment by baimard** [comment]
PHP version?

⁣Cordialement,
Benjamin AIMARD​

Le 28 févr. 2023 à 17:39, à 17:39, Antoine Gatineau ***@***.***> a écrit:

**Comment by infra-monkey** [comment]
/var/www/html $ php occ app:list | grep gestion
  - gestion: 2.3.2
/var/www/html $ php --version
PHP 8.1.16 (cli) (built: Feb 16 2023 01:31:00) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies
    
/var/www/html $ php occ status
  - installed: true
  - version: 25.0.3.2
  - versionstring: 25.0.3
  - edition: 
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false

**Comment by infra-monkey** [comment]
Definitvely looks like a lower case issue.
I changed the code to `return $res[0]['last_insert_id'];` and now it creates the new quote/invoice with the correct id.

**Comment by baimard** [comment]
Very strange that only affect your system.
Thank you so much for your help !

**Comment by baimard** [comment]
I will push the new version this night or tomorow

**Comment by infra-monkey** [comment]
Not sure how many people have updated to gestion >2.3.0 and use Postgres and use gestion. 
Pretty sure it’s a low number. 
Most home users are MySQL and big deployments wouldn’t use gestion I guess.
Thank you for your reactivity and for the software again. 
I ‘m good for a few weeks so no rush on my side
Télécharger BlueMail pour Mobile <https://bluemail.me/> 
Benjamin wrote:
I will push the new version this night or tomorow

**Comment by baimard** [comment]
Tell me if the bug is corrected by version 2.3.3

**Comment by infra-monkey** [comment]
It looks good with v 2.3.3

Merci bien Benjamin !

**Comment by baimard** [comment]
Merci à vous pour la remonté du bug :)

Don't forget, If your like my work :

Buy me a coffee and share a message : https://www.buymeacoffee.com/benjaminaimard
Share my project
Leave me a comment : https://apps.nextcloud.com/apps/gestion
thank you for support !
