### ISSUE TITLE
[FR] Réécriture lien 

### ISSUE THREAD

**Issue by 2r2y** [baimard/gestion#33]
Bonjour, 

J'ai un problème de réécriture dans les liens avec votre application. 

![image](https://user-images.githubusercontent.com/93328040/139257583-994b17aa-0c61-4905-ac76-52083d1e88e8.png)
![image](https://user-images.githubusercontent.com/93328040/139257712-63a9b7dd-64c0-46ae-9f5d-59f01e2f7f44.png)

Tout les liens sont incorrects dans l'application. 

Merci pour votre aide

**Comment by baimard** [comment]
Bonjour est ce que cela a corrigé votre problème ?

**Comment by 2r2y** [comment]
Bonjour, 

Je confirme le bon fonctionnement. 

Merci à vous
