### ISSUE TITLE
[FR] ajout de fonctionnalité - rendre possible l'édition de facture sans faire de devis

### ISSUE THREAD

**Issue by ourssansplus** [baimard/gestion#337]
Bonjour ! Pour certaines prestations, il n'est pas nécessaire de faire un devis.
Est-il possible de rendre possible l'édition d'une facture SANS passer par l'étape "Devis" ?
Merci 👍

**Comment by baimard** [comment]
Bonjour, malheureusement le design de l'application ne permet pas du tout cette démarche. Avant chaque prestation le client doit accepter un devis. Sinon vous avez besoin d'une caisse enregistreuse.

J'envisagerais éventuellement cette fonction.
