### ISSUE TITLE
Email is not send

### ISSUE THREAD

**Issue by connectnet** [baimard/gestion#345]
**Describe the bug**
After creating an offer or invoice I cant send an email to customer
PDF is creating well. nextcloud version 26.02

Thanks for your attention.

**Comment by baimard** [comment]
Thank you for repporting. I will check on this new version

**Comment by connectnet** [comment]
Great! 
Changing this in php.ini doesnt helps: 
```
upload_max_filesize 64M
post_max_size 64M
max_execution_time 300
value max_input_time 300
```

**Comment by baimard** [comment]
Please paste the error message in this issue.

**Comment by connectnet** [comment]
`Ist Ihr globaler Mailserver in Nextcloud konfiguriert?`
Is there a log file where I can get more details?

**Comment by connectnet** [comment]
Hello again! 
You are asking for more details from the nextcould .log file. Maybe you can find a little bit easier the bug: :-)

`{"reqId":"F5ZCf9JUa9MEU64Y9IV4","level":3,"time":"2023-06-27T14:16:29+00:00","remoteAddr":"192.168.77.4","user":"xxxxxx","app":"index","method":"POST","url":"/apps/gestion/sendPDF","message":"Symfony\\Cot\\Mime\\Part\\TextPart::__construct(): Argument #3 ($subtype) must be of type string, null given, called in /var/www/nextcloud/3rdparty/symfony/mime/Part/DataPart.php on line 45 in file '/var/www/nextcldparty/symfony/mime/Part/TextPart.php' line 45","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/100.0.0.0","version":"26.0.2.1","exc":{"Exception":"Exception","Message":"Symfony\\Component\\Mime\\Part\\TextPart::__construct(): Argument #3 ($subtype) must be of type string, null given, called in /var/www/nextcloud/3rdparty/symfony/mim/DataPart.php on line 45 in file '/var/www/nextcloud/3rdparty/symfony/mime/Part/TextPart.php' line 45","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":183,"functionpatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"filer/www/nextcloud/lib/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}e":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"TypeError","Message":"Symfony\\Component\\Mime\\Part\\TextPart::__construct(): Argument #3 ($subtyst be of type string, null given, called in /var/www/nextcloud/3rdparty/symfony/mime/Part/DataPart.php on line 45","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/symfony/mime/Part/DataPart.php","45,"function":"__construct","class":"Symfony\\Component\\Mime\\Part\\TextPart","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mime/Email.php","line":552,"function":"__construct","class":"Symfomponent\\Mime\\Part\\DataPart","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mime/Email.php","line":509,"function":"createDataPart","class":"Symfony\\Component\\Mime\\Email","type":"->","args* sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/mime/Email.php","line":466,"function":"prepareParts","class":"Symfony\\Component\\Mime\\Email","type":"->"},{"file":"/v/nextcloud/3rdparty/symfony/mime/Email.php","line":426,"function":"generateBody","class":"Symfony\\Component\\Mime\\Email","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mime/Message.php","lin,"function":"getBody","class":"Symfony\\Component\\Mime\\Email","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mime/RawMessage.php","line":52,"function":"toIterable","class":"Symfony\\Componene\\Message","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/Stream/AbstractStream.php","line":112,"function":"toIterable","class":"Symfony\\Component\\Mime\\RawMessage","t->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/SmtpTransport.php","line":206,"function":"replace","class":"Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\AbstractStream","t::"},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/AbstractTransport.php","line":72,"function":"doSend","class":"Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport","type":"->"},{:"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/SmtpTransport.php","line":136,"function":"send","class":"Symfony\\Component\\Mailer\\Transport\\AbstractTransport","type":"->"},{"file":"/var/wtcloud/3rdparty/symfony/mailer/Mailer.php","line":45,"function":"send","class":"Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport","type":"->"},{"file":"/var/www/nextcloud/lib/private/Mail/Maile,"line":217,"function":"send","class":"Symfony\\Component\\Mailer\\Mailer","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Controller/PageController.php","line":347,"function":"send","class":"Ol\\Mailer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"sendPDF","class":"OCA\\Gestion\\Controller\\PageController","type":"->"},{"file":"ww/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFrk/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\mework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"haquest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/symfony/mime/Part/TextPart.php","Line":45},"CustomMessage":"--"}}
(END)
`
Best Regards and thanks for that very useful app!

**Comment by baimard** [comment]
I confirm there is a bug in nextcloud 27.0.0 ...

**Comment by connectnet** [comment]
But Im using vers. 26.0.2?

**Comment by cedricbonhomme** [comment]
Emails are not sent for as well with Nextcloud version  26.0.3.

**Comment by baimard** [comment]
It's du to mimes part release in 2.4.0

**Comment by baimard** [comment]
Please let me see if the bug is solved

**Comment by cedricbonhomme** [comment]
This fixes the issue for me. Tested with Nextcloud 27.0.0.
