### ISSUE TITLE
Typo in hyperlink

### ISSUE THREAD

**Issue by flammableliquids** [baimard/gestion#347]
https://github.com/baimard/gestion/blob/7f6988127947a80e76e0f300e324ed986ed00655/templates/content/changelog.php#L6C3-L6C3

There is a typo in the hyperlink at this line

**Comment by baimard** [comment]
Oups merci !

⁣Cordialement,
Benjamin AIMARD​

Le 28 juin 2023 à 05:15, à 05:15, flammableliquids ***@***.***> a écrit:

**Comment by baimard** [comment]
2.4.0
