### ISSUE TITLE
NEED Qucik and Dirty way to change BID VALID 1 MONTH to BID VALID 1 WEEK or custom text 

### ISSUE THREAD

**Issue by les-les** [baimard/gestion#358]
need a quick and dirty way to change BID VALID 1 MONTH to BID VALID 1 WEEK 

any hints how to get there and change this 
1 Month not possible with those price gaps out there 

br LES

**Comment by baimard** [comment]
Direct in template

$NEXTCLOUDFOLDER/apps/gestion/templates

[                <div class="col col-xl mb-3 text-center"><b><span><?php p($l->t('Offer valid for 1 month from'));?> : </span><span><?php echo (new DateTime($_['devis'][0]->date))->format('d-m-Y'); ?></span></b></div>](https://github.com/baimard/gestion/blob/899d0122b20da229b51e096b303b65f76ec427e4/templates/content/devisshow.php#L43C106-L43C106)

**Comment by les-les** [comment]
thx ! 
saved my day !!

changed it here ;) 

$NEXTCLOUDFOLDER/apps/gestion/templates/content/devisshow.php
