### ISSUE TITLE
Sadly, nothing works.. [object Object] error

### ISSUE THREAD

**Issue by Thatoo** [baimard/gestion#360]
**Describe the bug**
When I reach the page, I'm welcomed with 3 error `[object Object]`.
I can't choose the folder where to save.
If I go to apps/gestion/config, I'm welcomed also with `[object Object]` object and everything is "loading".
In the console of the web browser, it says : 

XHR PROPFIND https://MYNEXTCLOUD.fr/nuage-nextcloud/apps/gestion/getStats
[HTTP/2 405 Method Not Allowed 76ms]

XHR PROPFIND
https://MYNEXTCLOUD.fr/nuage-nextcloud/apps/gestion/getConfiguration
[HTTP/2 405 Method Not Allowed 74ms]

XHR PROPFIND
https://MYNEXTCLOUD.fr/nuage-nextcloud/apps/gestion/getConfiguration
[HTTP/2 405 Method Not Allowed 156ms]

XHR PROPFIND
https://MYNEXTCLOUD.fr/nuage-nextcloud/apps/gestion/getClients
[HTTP/2 405 Method Not Allowed 83ms]

Uncaught ReferenceError: showError is not defined
    onload https://MYNEXTCLOUD.fr/nuage-nextcloud/apps/gestion/js/client.app.js?v=5aeb03f3-0:2
    loadClientDT https://MYNEXTCLOUD.fr/nuage-nextcloud/apps/gestion/js/client.app.js?v=5aeb03f3-0:2
    <anonymous> https://MYNEXTCLOUD.fr/nuage-nextcloud/apps/gestion/js/client.app.js?v=5aeb03f3-0:2
    EventListener.handleEvent* https://leprette.fr/nuage-nextcloud/apps/gestion/js/client.app.js?v=5aeb03f3-0:2
    <anonymous> https://MYNEXTCLOUD.fr/nuage-nextcloud/apps/gestion/js/client.app.js?v=5aeb03f3-0:2
    <anonymous> https://MYNEXTCLOUD.fr/nuage-nextcloud/apps/gestion/js/client.app.js?v=5aeb03f3-0:2

**Screenshots**
![image](https://github.com/baimard/gestion/assets/464782/34742a41-9b20-4830-9ee5-19d83e24f380)

![image](https://github.com/baimard/gestion/assets/464782/05f1ecb1-9306-4e0c-9ff4-d7f238ab3f55)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser Firefox 115

**Additional context**
Nextcloud is installed thanks to Yunohost.

**Comment by baimard** [comment]
Dear, you need javascript working on your web browser.

**Comment by Thatoo** [comment]
Well, I guess it does. I mean everything else is working, in nextcloud and other platforms.
I'll try in private navigation in case it is linked to an extension.

**Comment by baimard** [comment]
HAve you find the solution ?

**Comment by Thatoo** [comment]
No, unfortunately, I didn't find any solution so far.
Could it be linked to the yunohost nginx.conf file, https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/conf/nginx.conf or the extra_php-fpm.conf, https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/conf/extra_php-fpm.conf ?

**Comment by barzine** [comment]
Hi,

Have you maybe added gestion at some point and deleted the database or something around these lines?

I had the same exact behaviour on the client side of the gestion module that you described here before as the database was deleted at some point in our nextcloud instance. 

I was able to generate the database again by running the different migrations script as advised in https://github.com/baimard/gestion/issues/362#issuecomment-1786001331

**Comment by Thatoo** [comment]
No and the error doesn't seem to be related to a database issue.

**Comment by baimard** [comment]
I'm pretty sur that you have a problem with your reverse proxy. Because of the method not allowed. If you don't have proxy then it's with your php server.

Have you logs information?

**Comment by Thatoo** [comment]
I agree but I don't really know what to change in these files, the yunohost nginx.conf file, https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/conf/nginx.conf or the extra_php-fpm.conf, https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/conf/extra_php-fpm.conf ?

**Comment by Thatoo** [comment]
PHP system information given by nextcloud is : 

Version : 8.2.12
Limite de mémoire : 512 MB
Max Execution Time: 3600
Taille de téléversement maximale : 10 GB
Extensions : Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Comment by Thatoo** [comment]
What is weird is that I had never faced any issue before with any nextcloud's app using nextcloud on Yunohost. So this error is very specific to Gestion app.

**Comment by Thatoo** [comment]
The solution was given by tituspijean. Thanks to him.

Edit /etc/nginx/conf.d/<nextcloud domain>.d/nextcloud.conf to have on line 138 if ($request_method ~ ^(PUT|DELETE|PATCH|PROPFIND|PROPPATCH)$) {

and it works.

I’ll report to nextcloud’s yunohost app.
