### ISSUE TITLE
How to recreate the original table in the database

### ISSUE THREAD

**Issue by barzine** [baimard/gestion#362]
Hi,
Could you please point me where I can find the description of the tables I should have in the Nexcloud database for the gestion app?
These were deleted at some point in our database after the application was removed last time and are not reinstalled with the new installation of the application.

**Comment by baimard** [comment]
Dear, I forgot your message sorry.

You can find it in https://github.com/baimard/gestion/tree/master/lib/Migration, you need to execute all the file one by one

**Comment by barzine** [comment]
Thank you so much!
I had to figure out a little bit more after your hint. But everything seems to work again now.  😄 

--- For future reference, here is what I have done to get the table created by nextcloud again:

I have edited config.php (in nexcloud/config directory), and I have added ` 'debug' => true,  ` to the `$CONFIG` array (because I didn't have the field described at all)
Then I run sequentially the scripts in lib/Migration from the root directory of nexcloud: 

```
sudo -u www-data ./occ migration:execute gestion 7Date20220125174818
sudo -u www-data ./occ migration:execute gestion 20204Date20230202010101
sudo -u www-data ./occ migration:execute gestion 20203Date20230115010101
sudo -u www-data ./occ migration:execute gestion 20104Date20220728143910
sudo -u www-data ./occ migration:execute gestion 20007Date20220311135612
sudo -u www-data ./occ migration:execute gestion 20006Date20220223222222
sudo -u www-data ./occ migration:execute gestion 20002Date20220201085856
```

Finally, I edited config.php to its original state
