### ISSUE TITLE
Feature Request multiple companies

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [baimard/gestion#373]
It would be nice if it would be possible to manage multiple companies per user.

**Comment by baimard** [comment]
Hello, it's plan in 2.5.0 :

(left)

![Capture d’écran du 2024-01-08 13-32-51](https://github.com/baimard/gestion/assets/7591697/cdc03593-3bbf-4c63-9cc6-1a03a138e6d5)

**Comment by GVLLIFESTYLE** [comment]
perfect

**Comment by baimard** [comment]
85% done ...

**Comment by baimard** [comment]
If you want I release the 2.5.0 that integrate this feature
