### ISSUE TITLE
When opening Invoice: Internal server error. The request could not be processed by the server.

### ISSUE THREAD

**Issue by kirillvb** [baimard/gestion#378]
**Describe the bug**
When generating an Invoice, at the bottom of the document there is a frame with an error notification. This inscription is saved inside the PDF document

**To Reproduce**
1. Go to 'Quotes'
2. Click on 'Select Quote and click Open button'
3. Scroll down to 'down'
4. See error ( Internal server error. The request could not be processed by the server)

**To Reproduce**
1. Go to 'Invoices'
2. Click on 'Select invoice and click Open button'
3. Scroll down to 'down'
4. See error ( Internal server error. The request could not be processed by the server)

**Expected behavior**
Save the file without an error message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Nextcloud Hub 6 (27.1.4) SNAP
 - OS: Windows
 - Browser chrome, mozilla
 - Version [The problem was first noticed by me a year ago on previous versions of the software.]

**Additional context**
![gestion-error](https://github.com/baimard/gestion/assets/83208077/d76239f5-bb89-423e-840e-5088ad798b0d)

**Comment by baimard** [comment]
Hello maybe a problem with translation. What language do you use ?

**Comment by kirillvb** [comment]
Language = Russian. For me this is no longer relevant. Firstly, I couldn’t find how to switch to English, and secondly, the specifics of the accounts are not suitable at all, I couldn’t configure the necessary custom fields. I couldn't even add my account. I continue to use Word+Excel (
Thank you

**Comment by baimard** [comment]
Thank you too for your feedback. Just for informaiton you can change langage in the global nextcloud parameters.
