### ISSUE TITLE
Can't edit customers in offer / nextcloud #28

### ISSUE THREAD

**Issue by ctc** [baimard/gestion#379]
devis.app.js?v=dd69b92b-7:54716 Uncaught TypeError: el.forEach is not a function
    at checkSelectPurJs (devis.app.js?v=dd69b92b-7:54716:8)

replaced checkSelectPurJs(selectElement); with  checkSelect(selectElement); in  static loadClientList_cid(e){

same in js/facture.app.js

**Comment by baimard** [comment]
Master branch ?

**Comment by ctc** [comment]
Master branch does not work with nextcloud 28, can't test now, before switch to dev-2023 I had the problem with 2.4.3

**Comment by cedricbonhomme** [comment]
I confirm. Same issue on my side, with Nextcloud 28.

Here is a screenshot:

![Screenshot_20240214_223201](https://github.com/baimard/gestion/assets/465400/86b0d451-034d-4eee-81e0-31299c06ea8c)

**Comment by cedricbonhomme** [comment]
On my side I have resolved the issue with a dirty fix:

![Screenshot_20240214_230130](https://github.com/baimard/gestion/assets/465400/5b003ace-1e79-48c6-8942-7aeaa8e03929)


the problem was on ``t.forEach``. I think that at some point ``t`` is undifined. So I've added a check as you can see in the screenshot (in the file apps/gestion/js/devis.app.js) .

**Comment by baimard** [comment]
This version is very dirty. I'm so sorry. New version will be release next month

**Comment by cedricbonhomme** [comment]
I  just did the same in ``facture.app.js`` to solve the same issue for the ``factures``.

**Comment by TheMiNuS** [comment]
I also confirm having that issue on the last version on NC28.
If you can apply the fix while you publish the update to support NC29 it will be much appreciated.

MiNuS

**Comment by baimard** [comment]
2.5.0 is deploy in Nightly, I need to clear some little bug and I will deploy the version 2.5.1.

For the plan maybe in the middle of May

**Comment by baimard** [comment]
V2.5.1 deploy and fix all bugs.
