### ISSUE TITLE
Change VAT to GST For Australia 

### ISSUE THREAD

**Issue by crawtechnology** [baimard/gestion#380]
Hi,
Is it possible to Change every thing that is VAT to GST ?

**Comment by baimard** [comment]
> Hi,
> Is it possible to Change every thing that is VAT to GST ?

Sorry I don't understand what is gst ?

**Comment by crawtechnology** [comment]
Hi,
Goods and services tax (GST) is a tax of 10% on most goods, services and other items sold or consumed in Australia. If your business is registered for GST, you have to collect this extra money (one-eleventh of the sale price) from your customers. You pay this to the Australian Taxation Office (ATO)

**Comment by baimard** [comment]
Immediately you can fork and replace vat by gst in PHP file.

Cordialement,

Benjamin AIMARD

+33 6 60 51 44 86



Le 12 févr. 2024, 06:47, à 06:47, crawtechnology ***@***.***> a écrit:

**Comment by crawtechnology** [comment]
Thanks
I will try that
