### ISSUE TITLE
bug select client cotacion

### ISSUE THREAD

**Issue by maestriacyber** [baimard/gestion#381]
**Describe the bug**
error when selecting the customer at the time of contact.
User language Portuguese-BR

**Reproduce**
1. Go to 'CREATE QUOTE'
2. Click 'Select customer'
3. Error field not enabled. Customer list is not loaded

**Expected behavior**
Open customer selection list.

**Screenshots**
If applicable, add screenshots to help explain your issue.
![erro cotaca](https://github.com/baimard/gestion/assets/162075698/16315888-1924-414a-86e1-14d4bfaaa350)

**Desktop (fill in the following information):**
    - OS: Windows
    - Browser [chrome,]
    - Version [2.4.3]

**Describe the bug**

**Comment by riotweb** [comment]
Same here
OS Windows 10
Browser Firefox 124.0.2 
Version 2.4.3
NC Version 28.0.4
Hosting: Shared host (netcup)

**Comment by baimard** [comment]
Have you fill customers section ?

**Comment by cm954** [comment]
Hi All
here the same issue.
Customer, product and company section filled out but can't add customer to my quote.
Here another ScreenShot
![image](https://github.com/baimard/gestion/assets/105798806/3a7735cc-c569-441f-bc14-7e147fc40810)

**Comment by baimard** [comment]
What's your next cloud version?

**Comment by cm954** [comment]
NC : 28.0.4
iam browsing with google chrome latest

**Comment by maestriacyber** [comment]
google chrome versão 120.0.6099.130 (Versão oficial) 64 bits Next cloud versão  28.0.2

**Comment by tonytonyistony** [comment]
Can confirm this does not work for me either.
Fresh install.
Tested in Firefox and Chrome.
1 customer created and 1 product created.
Cannot select customer in quote, and cannot select quote in invoice.

**Comment by darksidecorrales** [comment]
The same here.  Nextcloud v28.0.3.2 on a Raspberry Pi 4 using NextcloudPi.  When I try to generate quotes, the registered clients do not appear, and the same thing happens with the quotes when I try to generate invoices.  I have tried it from several browsers and devices without success.

**Comment by baimard** [comment]
What's the version of the database ?

**Comment by cm954** [comment]
What's the version of the database ?
do You mean the changelog column in the cofigutation table if yes its 9

Here it is i hope its what you need 
![image](https://github.com/baimard/gestion/assets/105798806/7e89cfd9-9a83-4c09-b0e0-533ce179a055)

and this console view
![image](https://github.com/baimard/gestion/assets/105798806/43424fcd-1d04-4c94-851a-e16234282bec)

**Comment by tonytonyistony** [comment]
> What's the version of the database ?

`mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper`

**Comment by cm954** [comment]
> > What's the version of the database ?
> 
> `mysql Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using EditLine wrapper`

oups here it is
10.6.12-MariaDB-1:10.6.12+maria~ubu2004

**Comment by baimard** [comment]
Ok I find a bug, I have a new release but it's a beta, does someone want to test ?

**Comment by cm954** [comment]
Yes im ok to test

**Comment by baimard** [comment]
I find the bug it's due to nextcloud 28.0.5 don't know why.

Nightly are published please be carefull if you are in production. BACKUP YOUR DB !

**Comment by baimard** [comment]
New release solve this bug, 2.5.1
