### ISSUE TITLE
Errormessage - when try to install

### ISSUE THREAD

**Issue by riotweb** [baimard/gestion#384]
**Describe the bug**
I tryed to install, Errormessage from NC was displayed

**To Reproduce**
1. Go to 'Apps, search Gestion'
2. Click on 'install'
-
4. See error:
Index name "fs_id_storage_size" for table "xxxxxx_filecache.bkp" collides with the constraint on table "xxxx_filecache".

**Expected behavior**
Install :)

**Desktop (please complete the following information):**
 - OS: Win 10 professional
 - Browser Firefox
 - Version 125.0.1
 - NC: 28.0.4
 - Shared Host installation

**Comment by baimard** [comment]
solved with last version ?
