### ISSUE TITLE
Cant upgrade to 2.5.0 beta / 2.5.1 release

### ISSUE THREAD

**Issue by ghost** [baimard/gestion#387]
**Describe the bug**
Cant upgrade to 2.5.0

**To Reproduce**
1. enable beta channel in nextcloud admin settings
2. version 2.5.0 appears in update list
3. click update app
4. an error appears:

Database error when running migration 20300Date20230714134445 for app gestion An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_gestion_client.id_configuration
could not enable apps 

**Expected behavior**
app updates to 2.5

**Desktop (please complete the following information):**
not relevant (server problem) - debian 12 accessing nextcloud via web interface in firefox

**Additional context**
I'm using the sqlite backend
Nextcloud instance gets broken until I disable the gestion app in command line
In addition, going back to nextcloud stable release channel and re-enabling gestion, the app is still broken with the same error message.

**Comment by baimard** [comment]
is it solved ?
