### ISSUE TITLE
2.5.1 lost links between society and clients, invoices, quotes...;(

### ISSUE THREAD

**Issue by patricesanchez** [baimard/gestion#390]
**Describe the bug**
On NC 28.0.5, Gestion 2.5.1 seems to lost links between enterprise and clients, invoices and quotes. Moreover, it shows all the products of all the users.

**To Reproduce**
1. Go to "gestion" application
2. Select your enterprise...

Console navigator errors : 
_Erreur dans les liens source : request failed with status 404
URL de la ressource : https://site-url/apps/gestion/js/client.app.js?v=802a0bd1-5
URL du lien source : focus-trap.esm.js.map_

_Erreur dans les liens source : Error: request failed with status 404
URL de la ressource : https://url-site/apps/gestion/js/client.app.js?v=802a0bd1-5
URL du lien source : focus-trap.esm.js.map_

**Expected behavior**
To see clients, quotes and invoices linked to the enterprise selected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Firefox 125]
 - 

**Additional context**

**Comment by baimard** [comment]
Dear Patrice ,what database do you used ?

**Comment by patricesanchez** [comment]
Thx for your quick reply : Php 8.1.2 + mariadb 10.6.16.

**Comment by baimard** [comment]
it's strange, can I accès to your instance ?

**Comment by patricesanchez** [comment]
I prefer not... I'll try other things tonight and go back to you after...Thx.

**Comment by patricesanchez** [comment]
To complete my issue, when I click on "clients" I obtain, in console : 
_L’utilisation d’XMLHttpRequest de façon synchrone sur le fil d’exécution principal est obsolète à cause de son impact négatif sur la navigation de l’utilisateur final._
_Erreur dans les liens source : request failed with status 404
URL de la ressource : https://site-url/apps/gestion/js/client.app.js?v=802a0bd1-5
URL du lien source : focus-trap.esm.js.map_

**Comment by baimard** [comment]
Ok but without databse I can't investigate ...

**Comment by baimard** [comment]
is your instance synchronise with openldap ?

**Comment by baimard** [comment]
> To complete my issue, when I click on "clients" I obtain, in console :
> _L’utilisation d’XMLHttpRequest de façon synchrone sur le fil d’exécution principal est obsolète à cause de son impact négatif sur la navigation de l’utilisateur final._

OK ... I need to investigate, very strange for product ...

**Comment by patricesanchez** [comment]
Bonjour,
Je crois que vous êtes français...
Sur github, je ne vois pas votre question sur openldap et votre déception
pour l'accès à l'instance...
Néanmoins, j'ai très peu de données sur la base donc je vous ai extrait les
données de l'appli gestion (cf pj) et non, je n'utilise pas openldap.
En tous cas, merci pour votre produit qui dépanne bien ;)
Bonne continuation à vous

**Comment by baimard** [comment]
Bonjour Patrice,
Oui effectivement je suis français, j'ai supprimé mes deux questions car j'ai noté l'erreur, j'en discutais avec des collègues à midi. Y a eu une dépréciation d'un composant que j'utilise. Je vais faire la mise à jour. Ce qui me fait peur par contre c'est que vous voyez tous les produits de tous les utilisateurs. J'espère qu'il n'y a pas eu de problème à la migration.

Merci de vos encouragements, je sais que l'application est très pratique + de 3000 Téléchargements sur l'ancienne version. J'admets avoir un peu de mal à suivre les mises à jour de Nextcloud mais je vais y arriver :). De toute façon il est important pour la sécurité que je fasse évoluer mes composants :)

**Comment by patricesanchez** [comment]
Rebonjour,

Je vais me permettre de coller le sql dans la suite de ce mail...Navré pour
la lisibilité...
Pour ce qui est de l'appli gestion, il faut avouer qu'avoir une gestion de
trésorerie/compta directement dans nextcloud c'est vraiment une excellente
idée ;)
De mon côté, je l'utilise pour une section associative où nous faisons un
tout petit peu de facturation donc le produit convient parfaitement. Il y a
des fonctionnalités à améliorer (image compressée dans le pdf) ou à
implémenter mais, étant moi aussi développeur, je compatis face à la
"wishlist"... ;)
Merci encore !

Patrice


-- phpMyAdmin SQL Dump
-- version 5.1.1deb5ubuntu1
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost
-- Généré le : jeu. 02 mai 2024 à 12:42
-- Version du serveur : 10.6.16-MariaDB-0ubuntu0.22.04.1
-- Version de PHP : 8.1.2-1ubuntu2.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `3dmakers`
--

-- --------------------------------------------------------

--
-- Structure de la table `oc_gestion_client`
--

CREATE TABLE `oc_gestion_client` (
  `id` int(11) NOT NULL,
  `nom` longtext NOT NULL,
  `prenom` longtext NOT NULL,
  `legal_one` longtext NOT NULL,
  `entreprise` longtext NOT NULL,
  `telephone` longtext NOT NULL,
  `mail` longtext NOT NULL,
  `adresse` longtext NOT NULL,
  `id_configuration` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Déchargement des données de la table `oc_gestion_client`
--

INSERT INTO `oc_gestion_client` (`id`, `nom`, `prenom`, `legal_one`,
`entreprise`, `telephone`, `mail`, `adresse`, `id_configuration`) VALUES
(1, 'Lescure', 'Olivier', 'Siret', 'CSL Techniques Brassicoles',
'0600000000', ***@***.***', 'Fort de rosny', 3),
(2, 'Martin', 'R&eacute;gis', 'Siret', 'Fort de Rosny', '0600000001', '
***@***.***', 'Fort de rosny', 3),
(3, 'Nom', 'Prénom', 'Siret', 'STIG', 'Téléphone', 'E-mail', 'Adresse', 3),
(4, 'Nom', 'Prénom', 'Siret', 'CDF', 'Téléphone', 'E-mail', 'Adresse', 3),
(8, 'Brubion', 'Rudy', 'Siret', 'STIG', 'Téléphone', 'E-mail', 'Adresse',
3),
(10, 'BRUBION', 'Rudy', '', 'CSL', '', '
***@***.***', '', 5),
(11, 'LE BRAS', 'Mikael', '', 'Section', '0625583108', ***@***.***',
'', 5),
(12, 'DROGON', 'Kevin', '', 'CSL', '', ***@***.***', '', 5),
(13, 'NATIVEL', 'Xavier', '-', 'CSL', '-', '
***@***.***', '-', 5),
(14, 'BARBE', 'Sebastien', '-', 'CSL', '0646481969', '
***@***.***', '-', 5),
(15, 'DUBOIS', 'Olivier', '', 'Externe', '', '
***@***.***', '', 5);

-- --------------------------------------------------------

--
-- Structure de la table `oc_gestion_configuration`
--

CREATE TABLE `oc_gestion_configuration` (
  `id` int(11) NOT NULL,
  `entreprise` longtext NOT NULL,
  `nom` longtext NOT NULL,
  `prenom` longtext NOT NULL,
  `legal_one` longtext NOT NULL,
  `legal_two` longtext NOT NULL,
  `mail` longtext NOT NULL,
  `telephone` longtext NOT NULL,
  `adresse` longtext NOT NULL,
  `path` longtext NOT NULL,
  `mentions_default` varchar(255) NOT NULL DEFAULT 'Legales mentions',
  `tva_default` double NOT NULL DEFAULT 0,
  `changelog` varchar(255) NOT NULL DEFAULT '0',
  `devise` varchar(255) NOT NULL DEFAULT 'EUR',
  `auto_invoice_number` int(11) NOT NULL DEFAULT 1,
  `id_nextcloud` varchar(64) NOT NULL,
  `format` varchar(10) NOT NULL DEFAULT 'en-EN',
  `facture_prefixe` varchar(255) DEFAULT 'INVOICE-'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Déchargement des données de la table `oc_gestion_configuration`
--

INSERT INTO `oc_gestion_configuration` (`id`, `entreprise`, `nom`,
`prenom`, `legal_one`, `legal_two`, `mail`, `telephone`, `adresse`, `path`,
`mentions_default`, `tva_default`, `changelog`, `devise`,
`auto_invoice_number`, `id_nextcloud`, `format`, `facture_prefixe`) VALUES
(1, '3DMakers', '-', 'CSL Rosny sous Bois', '', '', '
***@***.***', '', '1 boulevard Th&eacute;ophile Sueur -
93110 ROSNY SOUS BOIS', '/.gestion', 'Les pi&egrave;ces produites ne
r&eacute;pondent pas aux exigences normatives de leur &eacute;quivalent
industriel. Aussi, le CSL 3D Makers ne saurait &ecirc;tre tenu pour
responsable des risques et dommages qui pourraient &ecirc;tre subis.', 0,
'9', 'EUR', 1, 'patrice', 'fr-FR', 'FACTURE'),
(3, 'CSL Rosny', '3D Makers', 'Section', 'Association loi 1901', '', '
***@***.***', '', 'CSL Rosny - 1 bd theophile sueur, 93110
Rosny-sous-Bois', '/Documents', 'Toutes les mentions légales, conditions ou
tout ce que vous souhaitez mettre dans le pied de page.', 0, '9', 'EUR', 1,
'Mik-L', 'fr-FR', 'FACTURE'),
(5, 'CSL ROSNY SOUS BOIS', '', '3D Makers', '', '', '
***@***.***', '', '1 boulevard Th&eacute;ophile Sueur -
Rosny sous Bois', '/Factures', 'Les pi&egrave;ces produites ne
r&eacute;pondent pas aux exigences normatives de leur &eacute;quivalent
industriel. Aussi, le CSL 3D Makers ne saurait &ecirc;tre tenu pour
responsable des risques et dommages qui pourraient &ecirc;tre subis.', 0,
'9', 'EUR', 1, 'tresorier', 'fr-FR', 'INVOICE');

-- --------------------------------------------------------

--
-- Structure de la table `oc_gestion_conf_share`
--

CREATE TABLE `oc_gestion_conf_share` (
  `id` int(11) NOT NULL,
  `id_nextcloud` longtext NOT NULL,
  `id_configuration` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- --------------------------------------------------------

--
-- Structure de la table `oc_gestion_devis`
--

CREATE TABLE `oc_gestion_devis` (
  `id` int(11) NOT NULL,
  `date` date NOT NULL,
  `num` longtext NOT NULL,
  `comment` varchar(255) NOT NULL DEFAULT 'comment',
  `version` varchar(64) NOT NULL DEFAULT '1.0',
  `mentions` varchar(255) NOT NULL DEFAULT 'New',
  `id_client` int(11) NOT NULL,
  `user_id` int(11) NOT NULL DEFAULT 0,
  `id_configuration` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Déchargement des données de la table `oc_gestion_devis`
--

INSERT INTO `oc_gestion_devis` (`id`, `date`, `num`, `comment`, `version`,
`mentions`, `id_client`, `user_id`, `id_configuration`) VALUES
(7, '2023-12-13', '2023-0001', 'Commentaire', '0.1', 'Nouveau', 10, 1, 5),
(9, '2023-12-13', '2023-0002', 'Commentaire', '0.1', 'Nouveau', 11, 2, 5),
(10, '2024-01-24', '2024-0001', 'Commentaire', '0.1', 'Nouveau', 12, 3, 5),
(11, '2024-01-29', '2024-0002', 'Commentaire', '0.1', 'Nouveau', 13, 4, 5),
(12, '2024-02-14', '2024-0003', 'Commentaire', '0.1', 'Nouveau', 14, 5, 5),
(13, '2024-02-15', 'Numéro de devis', 'Commentaire', '0.1', 'Nouveau', 0,
1, 3),
(14, '2024-02-16', '2024-0004', 'Commentaire', '0.1', 'Nouveau', 15, 6, 5);

-- --------------------------------------------------------

--
-- Structure de la table `oc_gestion_facture`
--

CREATE TABLE `oc_gestion_facture` (
  `id` int(11) NOT NULL,
  `num` longtext NOT NULL,
  `date` varchar(64) NOT NULL,
  `date_paiement` date NOT NULL,
  `type_paiement` varchar(64) NOT NULL,
  `status_paiement` varchar(64) NOT NULL DEFAULT 'NC',
  `version` varchar(64) NOT NULL DEFAULT '1.0',
  `id_devis` int(11) NOT NULL,
  `user_id` int(11) NOT NULL DEFAULT 0,
  `id_configuration` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Déchargement des données de la table `oc_gestion_facture`
--

INSERT INTO `oc_gestion_facture` (`id`, `num`, `date`, `date_paiement`,
`type_paiement`, `status_paiement`, `version`, `id_devis`, `user_id`,
`id_configuration`) VALUES
(6, 'INVOICE-1', '14/12/2023', '2023-12-14', 'Esp&egrave;ces', 'NC', '1.0',
7, 1, 5),
(7, 'INVOICE-2', '14/12/2023', '2023-12-14', 'Esp&egrave;ces', 'NC', '1.0',
9, 2, 5),
(8, 'INVOICE-3', '24/01/2024', '2024-01-24', 'Esp&egrave;ces', 'NC', '1.0',
10, 3, 5),
(9, 'INVOICE-4', '29/01/2024', '2024-01-29', 'Esp&egrave;ces', 'NC', '1.0',
11, 4, 5),
(10, 'INVOICE-5', '14/02/2024', '2024-02-14', 'Esp&egrave;ces', 'NC',
'1.0', 12, 5, 5),
(11, 'INVOICE-6', 'Texte libre', '2024-02-16', 'Esp&egrave;ces', 'NC',
'1.0', 14, 6, 5);

-- --------------------------------------------------------

--
-- Structure de la table `oc_gestion_produit`
--

CREATE TABLE `oc_gestion_produit` (
  `id` int(11) NOT NULL,
  `reference` longtext NOT NULL,
  `description` longtext NOT NULL,
  `prix_unitaire` double NOT NULL DEFAULT 0,
  `vat` double NOT NULL DEFAULT 0,
  `id_configuration` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Déchargement des données de la table `oc_gestion_produit`
--

INSERT INTO `oc_gestion_produit` (`id`, `reference`, `description`,
`prix_unitaire`, `vat`, `id_configuration`) VALUES
(2, 'Carnet Ext&eacute;rieur', 'Carnet cr&eacute;dit&eacute; de 10&euro;
pour personne ext&eacute;rieur', 10, 0, 3),
(3, 'Carnet CSL', 'Carnet cr&eacute;dit&eacute; de 11&euro; pour personne
membre d&#039;un CSL', 10, 0, 3),
(4, 'Carnet Section', 'Carnet cr&eacute;dit&eacute; de 12&euro;pour
personne membre de la section', 10, 0, 3),
(7, '1', 'CSL 11 consommables', 10, 0, 1),
(8, '2', 'Section 12 consommables', 10, 0, 1),
(9, '3', 'Bonus section (2 consommables)', -2, 0, 1),
(10, '4', 'Consommable', 1, 0, 1),
(12, '5', 'Avoir', -1, 0, 1),
(16, '6', 'Externe - 10 consommables', 10, 0, 1),
(17, 'Carnet Ext&eacute;rieur', 'Carnet cr&eacute;dit&eacute; de 10&euro;
pour personne ext&eacute;rieure', 10, 0, 5),
(18, 'Carnet CSL', 'Carnet cr&eacute;dit&eacute; de 11&euro; pour personne
membre d&#039;un CSL', 10, 0, 5),
(19, 'Carnet Section', 'Carnet cr&eacute;dit&eacute; de 12&euro;pour
personne membre de la section', 10, 0, 5);

-- --------------------------------------------------------

--
-- Structure de la table `oc_gestion_produit_devis`
--

CREATE TABLE `oc_gestion_produit_devis` (
  `id` int(11) NOT NULL,
  `devis_id` int(11) NOT NULL,
  `produit_id` int(11) NOT NULL,
  `quantite` double NOT NULL DEFAULT 0,
  `discount` double NOT NULL DEFAULT 0,
  `comment` varchar(255) DEFAULT '-',
  `id_configuration` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Déchargement des données de la table `oc_gestion_produit_devis`
--

INSERT INTO `oc_gestion_produit_devis` (`id`, `devis_id`, `produit_id`,
`quantite`, `discount`, `comment`, `id_configuration`) VALUES
(1, 1, 3, 4, 0, '-', 3),
(2, 1, 5, 1, 0, '-', 3),
(9, 2, 7, 2, 0, '-', 1),
(12, 3, 15, 1, 0, '-', 1),
(13, 3, 12, 10, 0, '-', 1),
(14, 4, 12, 22, 0, '-', 1),
(15, 4, 10, 6, 0, '-', 1),
(16, 5, 16, 1, 0, '-', 1),
(17, 6, 2, 1, 0, '-', 3),
(20, 7, 18, 1, 0, '-', 5),
(22, 9, 19, 1, 0, '-', 5),
(26, 10, 18, 1, 0, '-', 5),
(27, 11, 18, 1, 0, '-', 5),
(31, 12, 18, 1, 0, '-', 5),
(32, 14, 17, 1, 0, '-', 5);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `oc_gestion_client`
--
ALTER TABLE `oc_gestion_client`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `oc_gestion_configuration`
--
ALTER TABLE `oc_gestion_configuration`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `oc_gestion_conf_share`
--
ALTER TABLE `oc_gestion_conf_share`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `oc_gestion_devis`
--
ALTER TABLE `oc_gestion_devis`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `oc_gestion_facture`
--
ALTER TABLE `oc_gestion_facture`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `oc_gestion_produit`
--
ALTER TABLE `oc_gestion_produit`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `oc_gestion_produit_devis`
--
ALTER TABLE `oc_gestion_produit_devis`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `oc_gestion_client`
--
ALTER TABLE `oc_gestion_client`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT pour la table `oc_gestion_configuration`
--
ALTER TABLE `oc_gestion_configuration`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT pour la table `oc_gestion_conf_share`
--
ALTER TABLE `oc_gestion_conf_share`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table `oc_gestion_devis`
--
ALTER TABLE `oc_gestion_devis`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;

--
-- AUTO_INCREMENT pour la table `oc_gestion_facture`
--
ALTER TABLE `oc_gestion_facture`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT pour la table `oc_gestion_produit`
--
ALTER TABLE `oc_gestion_produit`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;

--
-- AUTO_INCREMENT pour la table `oc_gestion_produit_devis`
--
ALTER TABLE `oc_gestion_produit_devis`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;
COMMIT;

/*!40101 SET ***@***.***_CHARACTER_SET_CLIENT */;
/*!40101 SET ***@***.***_CHARACTER_SET_RESULTS */;
/*!40101 SET ***@***.***_COLLATION_CONNECTION */;

**Comment by baimard** [comment]
Bonjour,
Une relance pour savoir si tout va bien à la suite des dernières mises à jour, je clos le ticket en suite.

**Comment by patricesanchez** [comment]
> Bonjour, Une relance pour savoir si tout va bien à la suite des dernières mises à jour, je clos le ticket en suite.

A priori, cela semble fonctionner. Néanmoins, mon besoin a évolué, je suis passé sur une autre solution. Bon courage ;)

**Comment by baimard** [comment]
Merci bon courage dans tes projets :pray:

**Comment by patricesanchez** [comment]
Merci ! A toi aussi ;)
