### ISSUE TITLE
Translation review - General

### ISSUE THREAD

**Issue by roliverio** [baimard/gestion#392]
Hi!, 

As i cannot directly participate in the RoadMap conversation, i would like to point out, being a member of the Transifex Team which is involved in Nextcloud translations, that this application has some grammar issues, and, of course, a lot of phrases that couldn't directly correlate to invoicing across many languages. I'm unsure if you have any internal documentation that clearly explains or at least gives context on each of the solutions features/operations/processes, which would help me do sensible work in improving the strings that have to be translated _on the code_, so they end up in Transifex as better strings to translate to, and thus, more locale-agnostic.

Please let me know if you have such a document (even if it's a very informal draft), so i can start doing some PRs here to start improving it.

Thanks!

**Comment by baimard** [comment]
Please see directly transifex community thanks !
