### ISSUE TITLE
Error with migrations from fresh install

### ISSUE THREAD

**Issue by QuentinFonteneau** [baimard/gestion#394]
First, thanks for this module and sorry for non-respect of issue format. 

On fresh install, I have a issue when I tried to install Gestion. 
SQL error like "oc_gestion_client" doesn't exist. 

This is  origin's issue and solution : 

You should rename your migration file [Version7Date20220125174818.php](https://github.com/baimard/gestion/blob/master/lib/Migration/Version7Date20220125174818.php) because it's mandatory to execute this migration first (contains tables creation).
I rename the class and file as Version20001Date20220125174818.php and all is OK

**Comment by QuentinFonteneau** [comment]
Damn, real origin is from my oc_migrations table that already contains migration Version7Date20220125174818...
Sorry !

**Comment by baimard** [comment]
Merci :)
