### ISSUE TITLE
Compatibility with NC 29

### ISSUE THREAD

**Issue by cedricbonhomme** [baimard/gestion#397]
**Describe the bug**

Gestion is displayed as not compatible with Nextcloud 29.  Is there any reason for this ?

**Comment by cedricbonhomme** [comment]
if I force the update there is SQLSTATE error:

```bash
cedric@ssh:~/www/membres$ php occ app:install gestion
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see https://www.php.net/manual/en/book.pcntl.php
Additionally the function 'pcntl_signal' and 'pcntl_signal_dispatch' need to be enabled in your php.ini.
Error: Database error when running migration 20300Date20230714134445 for app gestion
An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "id_configuration" of relation "oc_gestion_client" contains null values
```

but I cannot even find the column ``id_configuration``. So I guess it's due to a wrong migration.

**Comment by cedricbonhomme** [comment]
ok, for now I hacked the migration script. I added 'notnull => false' [here](https://github.com/baimard/gestion/blob/master/lib/Migration/Version20300Date20230714134445.php#L116) and [here](https://github.com/baimard/gestion/blob/master/lib/Migration/Version20300Date20230714134445.php#L136). Then the upgrade script worked. And there are correct values in the column ``id_configuration`` in the different tables.

**Comment by baimard** [comment]
Merci Cédric, dès que j'ai un instant je regarde. Je n'avais pas encore validé le passage en NC 29. Les release de NC sont vraiment rapide !

**Comment by Thatoo** [comment]
When compatibility will be ok, could you mention it here (when closing the issue) for us to know we can update to NC 29 please?
Thank you

**Comment by TheRealRWJ** [comment]
And Nextcloud 30 please

**Comment by baimard** [comment]
Nextcloud release are to quick ...

**Comment by baimard** [comment]
@cedricbonhomme je n'ai pas réussi à reproduire le bug, je vais appliquer le correctif comme tu l'as donné du coup.

Je te remercie infiniment .

**Comment by baimard** [comment]
done in 2.6.0
