### ISSUE TITLE
[EN] Error opening Invoices

### ISSUE THREAD

**Issue by Cdisk2022** [baimard/gestion#41]
when i open a Quote the link goes to:   MYSITE.com/index.php/apps/gestion/devis/1/show    and that is OK but when i try to open an invoice it goes to:  MYSITE.com/apps/gestion/facture/1/show      instead of   MYSITE.com/index.php/apps/gestion/facture/1/show.

if i make a direct link with the correct one the invoice opens! so it's missing the index.php in the link to open correctly the invoice.

**Comment by baimard** [comment]
I think, I made a mistake, i'm gone watch, thanks you for reporting :)

**Comment by Maingron** [comment]
Same problem over here. For me it goes from `https://████/cloud/apps/gestion/facture/1/show` -> `https://█████/apps/gestion/facture/1/show`, so it even leaves the `/cloud` folder

**Comment by baimard** [comment]
is it good for you ?
