### ISSUE TITLE
operator does not exist: integer ~~ unknown LINE 1: SELECT * FROM oc_gestion_configuration WHERE id LIKE $1

### ISSUE THREAD

**Issue by Caveflow** [baimard/gestion#416]
**Describe the bug**
I use the latest nextcloud aio together with gestion 2.6.2 and get this error:
```php
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: integer ~~ unknown LINE 1: SELECT * FROM oc_gestion_configuration WHERE id LIKE $1 ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts.
``` 
when I try to create an invoice.

I found this [Issue ](https://github.com/baimard/gestion/issues/398), which seems to be fixed, so I do not understand why I get this error with the current version.

**Comment by Piefje01** [comment]
foreach() argument must be of type array|object, null given at /var/www/nextcloud/apps/gestion/templates/content/configuration.php#36

**Comment by Piefje01** [comment]
{"reqId":"vNdXwPhEahBCyOp8GEBp","level":3,"time":"2024-11-11T09:27:44+01:00","remoteAddr":"192.168.2.94","user":"beheer","app":"index","method":"POST","url":"/apps/gestion/facture/insert","message":"An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer ~~ unknown\nLINE 1: SELECT * FROM oc_gestion_configuration WHERE id LIKE $1\n                                                        ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0","version":"30.0.1.2","exception":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer ~~ unknown\nLINE 1: SELECT * FROM oc_gestion_configuration WHERE id LIKE $1\n                                                        ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":7,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1939,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1881,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Statement.php","line":194,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/PreparedStatement.php","line":69,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":426,"function":"execute","class":"OC\\DB\\PreparedStatement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":154,"function":"execSQLNoJsonReturn","class":"OCA\\Gestion\\Db\\Bdd","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Controller/PageController.php","line":542,"function":"insertFacture","class":"OCA\\Gestion\\Db\\Bdd","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"insertFacture","class":"OCA\\Gestion\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php","Line":87,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer ~~ unknown\nLINE 1: SELECT * FROM oc_gestion_configuration WHERE id LIKE $1\n                                                        ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":7,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":132,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Statement.php","line":190,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/PreparedStatement.php","line":69,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":426,"function":"execute","class":"OC\\DB\\PreparedStatement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":154,"function":"execSQLNoJsonReturn","class":"OCA\\Gestion\\Db\\Bdd","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Controller/PageController.php","line":542,"function":"insertFacture","class":"OCA\\Gestion\\Db\\Bdd","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"insertFacture","class":"OCA\\Gestion\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":28,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer ~~ unknown\nLINE 1: SELECT * FROM oc_gestion_configuration WHERE id LIKE $1\n                                                        ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":"42883","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":130,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Statement.php","line":190,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/PreparedStatement.php","line":69,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":426,"function":"execute","class":"OC\\DB\\PreparedStatement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":154,"function":"execSQLNoJsonReturn","class":"OCA\\Gestion\\Db\\Bdd","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Controller/PageController.php","line":542,"function":"insertFacture","class":"OCA\\Gestion\\Db\\Bdd","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"insertFacture","class":"OCA\\Gestion\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":130}},"message":"An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer ~~ unknown\nLINE 1: SELECT * FROM oc_gestion_configuration WHERE id LIKE $1\n                                                        ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","exception":[],"CustomMessage":"An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer ~~ unknown\nLINE 1: SELECT * FROM oc_gestion_configuration WHERE id LIKE $1\n                                                        ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts."},"id":"6731c078b9285"}

**Comment by baimard** [comment]
I need more information,

Nextcloud version, database version etc ...

**Comment by Caveflow** [comment]
thanks for your answer, I use Nextcloud AIO (29.0.8) and:
![image](https://github.com/user-attachments/assets/e1b38eee-8d9e-46fe-a1ae-454296327560)

**Comment by Piefje01** [comment]
Add invoice gives a error <div id="nojavascript">
<div>

**Comment by baimard** [comment]
I'm soo sorry postgre sql is not supported by GESTION APP.
