### ISSUE TITLE
[EN] accents in folder names

### ISSUE THREAD

**Issue by Cdisk2022** [baimard/gestion#42]
if we create a folder where its name has accents (PT-PT language) after configuring the folder where we keep  "quote" and "invoice" documents, the name of the folders is automatically changed to an encoding other than UTF8-BOM.

If by chance we need to delete or rename the folder configured as the destination of the files before pointing to a new destination folder, nextcloud is in loading mode (possible timeout) and then copies of the folders are created with the original name

**Comment by baimard** [comment]
Could you shre me a screen of the folder ?

thank you for reporting !

**Comment by Cdisk2022** [comment]
![print 1](https://user-images.githubusercontent.com/94477857/142176496-5b049f4f-d3e9-4a09-91e5-70790ed706ad.png)
![print2](https://user-images.githubusercontent.com/94477857/142176501-2cb344e8-a1c6-4e69-b23a-c30774f80819.png)
![print3](https://user-images.githubusercontent.com/94477857/142176504-fee1b282-3ac0-4a2c-bb99-4a858f21c382.png)

Print1: creating folder with the name (Orçamentos)
Print2: The path automatically changed to Or&ccedil;amentos
Print3: Folders location in nextcloud files. The folder that i created its there but when we save a quote or a invoice the system creates a new folder (Or&ccedil;amentos) to put the files in because it's the path that Gestion is assuming.
The problem is between the step that we create the folder to put the files and the moment that the folder name is recorded on the database. i think that changing the fieldtype in the database will solve the problem.

i found a print in the net maybe it can help
[https://i.stack.imgur.com/UicoQ.png](url)

**Comment by baimard** [comment]
Ok, I confirm this is a bug, thank you for reporting.

It's because htmlentities.

I recommend for now to don't use special char for folder

**Comment by baimard** [comment]
1.3.1
