### ISSUE TITLE
No Javascript

### ISSUE THREAD

**Issue by SmokingBoar** [baimard/gestion#422]
**Describe the bug**
when attempting to add my first invoice i get a slideout saying "<div id="nojavascript">
<div>
This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page. </div>
</div>"

**To Reproduce**
1. Go to invoice
2. Click on add invoice
3. See error

**Expected behavior**
able to create invoice

**Screenshots**
![image](https://github.com/user-attachments/assets/ab7526e8-00e0-447f-a003-c30d7afac03e)
![image](https://github.com/user-attachments/assets/5e7da70c-895e-4102-b94e-d3659195c510)

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser chrome
 - Version 130.0.6723.117 

**Additional context**
i verified that i had javascript allowed as well

**Comment by Piefje01** [comment]
Any news on this?

**Comment by Piefje01** [comment]
Well thats no gonna work, even on my android it gives NO JAVA SCRIPT. It is enabled on IE CHROME, bu still can make no invoices.
