### ISSUE TITLE
[EN] Application does not open in nextcloud 22.2.0

### ISSUE THREAD

**Issue by ennyjr** [baimard/gestion#43]
I installed the app from the Nextcloud app store. But it doesn't open for nothing.
In log file:

  `"Exception":"ParseError","Message":"syntax error, unexpected 'String' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)",
`
Apache: 2.4.38-3+deb10u6
OS: Debian 11
PHP: 7.3

**Comment by baimard** [comment]
Hello ennyjr,
thank you for repporting.

Please update php to 7.4 :)

**Comment by ennyjr** [comment]
All right, it was the PHP version, I upgraded to 7.4 and it worked. Thanks
