### ISSUE TITLE
[EN] Translations not complete

### ISSUE THREAD

**Issue by Maingron** [baimard/gestion#44]
I've installed gestion into my Nextcloud 22.2, which, besides of #41, went pretty well.

Since I can't speak French, I rely on the English translations. There are many places where the translations are missing though. It'd be great if the English translations get prioritized and improved.

Once the English translation is 100%, I could also contribute a German translation.

**Comment by baimard** [comment]
Dear all the translation are in transifex. And you need to work with this tool !

Could you please tell me where the translation are not in english ?

**Comment by Maingron** [comment]
I've never heard of transifex. I'll have to take a look into it first.

Regarding places of missing translations, they are about everywhere. I also find some terms hard to understand, but that could just be on me. 

I personally think you should switch the default language to English, especially for an app like this.

A few places I can mention right now:
- Invoice -> Date of service -> Default value = Texte libre
- Quote -> Stats -> Default value = Création
- cloud/apps/gestion/facture/2/show -> Entire footer is not in English

![grafik](https://user-images.githubusercontent.com/47825439/142287506-2bc9b772-36a5-4452-bba0-def44788a010.png)

**Comment by baimard** [comment]
The default langage is in english, maybe some translation is in french because of hard coding.

But for the rooter it's very strange in version 1.2 the footer is a parameter
