### ISSUE TITLE
[EN] Darkmode unusable

### ISSUE THREAD

**Issue by Maingron** [baimard/gestion#45]
I'm using Nextcloud 22.2. Everything seems to be working, but the Darkmode of gestion is not working properly. Most of the times, texts are rendered gray on white when Nextclouds Darkmode theme is enabled. I've attached some screenshots.
I'm a Darkmode user and would consider gestion unusable in this state. 
![grafik](https://user-images.githubusercontent.com/47825439/142286503-2b9760ec-8585-4fcd-8f1a-cf6fa0d6e0f3.png)
![grafik](https://user-images.githubusercontent.com/47825439/142286614-80feb8aa-789b-4bc0-a0d6-39476bc7f5ee.png)
![grafik](https://user-images.githubusercontent.com/47825439/142286634-ce972753-eafa-49c2-9bbe-f920df61f4d7.png)
![grafik](https://user-images.githubusercontent.com/47825439/142286676-b69ae1f6-ff4e-4e1e-bf48-667eae0c24fc.png)

**Comment by baimard** [comment]
Keep in your mind that lot of apps in nextcloud are free and developed by lonely developers who try to contribute to a better world. It's very hard to satisfy everyone.

Your issue is taken into account.

**Comment by baimard** [comment]
Need tests
