### ISSUE TITLE
[EN] l10n: Context for "Your Limited company"

### ISSUE THREAD

**Issue by rakekniven** [baimard/gestion#46]
https://github.com/baimard/gestion/blob/57005a5ebe6b32377adc53208276152acb98b379/lib/Db/Bdd.php#L158

What does that mean?

**Comment by baimard** [comment]
I have tried to translate in english for "SIREN" "SIRET" which is unique number of a company in France. Maybe there is a better translation or an other way to do that.

**Comment by rakekniven** [comment]
Ok, understood your comment.
Did some research and english word will be "Company Identification Number".

What is the difference to line 159 ?:

https://github.com/baimard/gestion/blob/57005a5ebe6b32377adc53208276152acb98b379/lib/Db/Bdd.php#L159

**Comment by Norbert-D** [comment]
Also would be good to add the VAT No or Sales tax No different Names per country

**Comment by rakekniven** [comment]
> Also would be good to add the VAT No or Sales tax No different Names per country

Please do not hijack this issue 😁 

Please file a new one.

**Comment by Norbert-D** [comment]
Sorry, want happen again

**Comment by baimard** [comment]
> 

one is for "SIREN" and other is for "SIRET".

I think it maybe better to change this by "Global legal information" ?

what do you think about this ?

**Comment by larusalka** [comment]
> > 
> 
> one is for "SIREN" and other is for "SIRET".
> 
> I think it maybe better to change this by "Global legal information" ?
> 
> what do you think about this ?

"Tax identification number" can be a good option in English. This varies widely by country (https://en.m.wikipedia.org/wiki/VAT_identification_number), so it might be a good idea to have an option to customize the name of the field, or add custom fields as needed.
Hope that helps.

**Comment by baimard** [comment]
It's exactly the problem, In my mind it's better to set 2 inputs 

with legal information 1 and legal informaiton 2 in place of SIREN SIRET

**Comment by larusalka** [comment]
Yes, two inputs might work for many countries, as long as users can change the name of the fields (legal information 1&2), e.g. to use SIREN and SIRET in France. Otherwise, users would be limited by the existence of a localized version of the app for their country, for example, for Spanish and all the different Latin American variants.

**Comment by baimard** [comment]
I will change that in next version.

**Comment by baimard** [comment]
done
