### ISSUE TITLE
[EN] Polish law for a VAT invoice

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#47]
In Polish tax law, pursuant to Art. 106e of the VAT Act, the invoice should contain the following elements:

- Date of issue,
- Consecutive number of the invoice in accordance with the adopted numbering,
- Names and surnames or the name of the seller and buyer of the goods / services and their addresses,
- NIP number of the taxpayer (seller),
- NIP number by means of which the buyer is identified for the purposes of tax or value added tax,
- The date of the delivery or completion of the delivery of the goods or the performance of the service or the date of receipt of payment, if specified and different from the date of invoice,
- Name of the product or service,
- Measurement unit and quantity of goods or services sold,
- Net unit price of a good or service,
- The amount of any rebates, discounts and rebates,
- Net sales value,
- VAT rate and tax value,
- The sum of net sales, broken down into values ​​subject to individual tax rates and tax-free sales,
- VAT amounts broken down into individual rates,
- Total amount receivable.

I provide details that relate to the Polish law on VAT invoices. It may be useful to adapt the application so that it is also compliant with Polish law 😉.

**Comment by baimard** [comment]
What do you need to be compliant? (please make a list, forget VAT and discount please it's in developement)

**Comment by Valdnet** [comment]
To provide details, I have to wait until the new version of the application is released.

**Comment by Valdnet** [comment]
Should be adjusted:

1. Numbering sequence:
 - Consecutive number of the invoice in accordance with the adopted numbering (Issue: #18).

2. In the invoice header:

- NIP number of the taxpayer (seller),
- NIP number by means of which the buyer is identified for the purposes of tax or value added tax.

3. Invoice Items:

- Measurement unit of goods or services sold,
- Amounts of any price rebates or reductions, including in the form of an early payment rebate, unless included in the net unit price,
- VAT rate (Issue: #63).

4. Sales Summary:

- The sum of net sales, broken down into values ​​subject to individual tax rates and tax-free sales.

**Comment by baimard** [comment]
In the invoice header:
NIP number of the taxpayer (seller),
NIP number by means of which the buyer is identified for the purposes of tax or value added tax.

NIP number are "Limited company"

I will change this information by a better word that can be comprehensible in international context

**Comment by baimard** [comment]
in version 2.0 :
 
Section : Legal information one and legal information 2

**Comment by baimard** [comment]
where we are for this subject ?

**Comment by Valdnet** [comment]
We do not have this yet:
- Measurement unit of goods or services sold,
- The amount of any rebates, discounts and rebates,

After adding VAT rates for individual goods and services (issue: #63), you'll be missing:
- The sum of net sales, broken down into values ​​subject to individual tax rates and tax-free sales,
- VAT amounts broken down into individual rates,

**Comment by baimard** [comment]
Taken into account thank you

**Comment by baimard** [comment]
Numbering sequence:
Consecutive number of the invoice in accordance with the adopted numbering (Issue: https://github.com/baimard/gestion/issues/18).

done

**Comment by sirLeone** [comment]
It would be perfect to add possibility to set in VAT rate field that someone is exempted of paying VAT. In Poland you can decide to not paying VAT if your income is not greater than 200000PLN. In such case you must put text "Art. 113 ust. 1" as a legal basis for exemption of paying VAT.
