### ISSUE TITLE
[EN] Repeating the "Welcome to GESTION" window

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#50]
When selecting from the side menu, for example: "Customer", "Quote", "Invoice" or "Product", the "Welcome to GESTION" window appears for a **moment** each time.

Apps:
Nextcloud 22.2.3
Gestion 1.2.0

**Comment by baimard** [comment]
It appear until you configure your company information. (just click on configuration). It's normal.

Please read : "To start with this application you need to configure your company information, follow this link"

**Comment by Valdnet** [comment]
It shouldn't appear for a moment. There should be constant information.
