### ISSUE TITLE
[EN] Add button

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#52]
Adding a new customer, quote, invoice and product should not be done by:

![obraz](https://user-images.githubusercontent.com/47037905/142769024-5374d1cd-7752-4aec-ab1e-0a73a6016c69.png)

Only the path should be here.

Adding new items should be done through a separate button.

Apps:
Nextcloud 22.2.3
Gestion 1.2.0

**Comment by baimard** [comment]
Why not ?

**Comment by Valdnet** [comment]
It is not very intuitive for the application user 😉.

I suggest making buttons like when adding a product, e.g .:

![obraz](https://user-images.githubusercontent.com/47037905/142771657-ba57b440-1619-4381-8db2-760cfd4e0409.png)

**Comment by baimard** [comment]
I need to have a think
