### ISSUE TITLE
[EN] Add a mark setting for price

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#53]
Currently, the sign that separates decimal numbers in the price is only a dot:

![obraz](https://user-images.githubusercontent.com/47037905/142770279-f9a3a76a-5e08-4916-8f84-8957509c8e1b.png)

In my opinion, you should add a sign setting that is to separate decimals in the price. Different characters are used in different countries, e.g. in Poland it is a comma.

The setting should be in the currency options.

**Comment by baimard** [comment]
Done in last push :)

**Comment by baimard** [comment]
I'm not sure that all good. Please don't close. I'm interested to follow this issue

**Comment by baimard** [comment]
Embeded in 2.0.6
