### ISSUE TITLE
[EN] Adding a product in "Quote"

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#55]
When creating a Quote, by adding a product, I receive the following information:

![obraz](https://user-images.githubusercontent.com/47037905/142771980-c81dd779-b3b8-4898-9a61-31922f0958aa.png)

The product is added.

After refreshing the page, the product is added first in the list. The next time you click the "Add product" button, the above message is displayed again. The same product appears again after the page has been loaded.
My guess is that the window with the selection of products to add does not open for me.

![obraz](https://user-images.githubusercontent.com/47037905/142771904-1201b92b-f290-4e2c-a4fb-3856d462f7fd.png)

Then, when removing a product in Quote, I get the following information:

![obraz](https://user-images.githubusercontent.com/47037905/142772053-388cf6b0-1451-47a6-8bd6-c6813233bbaf.png)

Apps:
Nextcloud 22.2.3
Gestion 1.2.0

**Comment by Norbert-D** [comment]
Apps:
Nextcloud 22.2.3
Gestion 1.2.0
PHP 8.0

Creating a Product under "Product"  using "Add Product" this error appears:

**"Error: Too few arguments to function OCA\Gestion\Db\Bdd::insertProduit(), 1 passed in /var/www/nextcloud/apps/gestion/lib/Controller/PageController.php on line 241 and exactly 3 expected"**

with the pop-up [object Object]
No product can be added

**Comment by baimard** [comment]
Yes please update to 1.2.1

**Comment by baimard** [comment]
> Apps: Nextcloud 22.2.3 Gestion 1.2.0 PHP 8.0
> 
> Creating a Product under "Product" using "Add Product" this error appears:
> 
> **"Error: Too few arguments to function OCA\Gestion\Db\Bdd::insertProduit(), 1 passed in /var/www/nextcloud/apps/gestion/lib/Controller/PageController.php on line 241 and exactly 3 expected"**
> 
> with the pop-up [object Object] No product can be added

Norbert-D you're write, bug identify.

**Comment by baimard** [comment]
@Valdnet fix in last version 1.2.2, can you confirm that ok for you ?

**Comment by Valdnet** [comment]
When adding a product, only the first product from the product list is added automatically.
I still can't choose what product to add from the product list.

**Comment by baimard** [comment]
Is it possible to make me a short video ?

**Comment by Valdnet** [comment]
I found how to replace the product. If you double-click the product index. This is somewhat confusing to the user.

When adding a product, a product selection window should appear or create a new product with the information "Select a product":

![obraz](https://user-images.githubusercontent.com/47037905/143599422-e7f39d0a-2584-42c0-bb50-696858fcb040.png)

**Comment by baimard** [comment]
I need to add Title or more information, **thank you for your feedback.**
