### ISSUE TITLE
[EN] Information during menu navigation

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#57]
When navigating the application menu (Customer, Quote, etc.), the following message appears each time:

![obraz](https://user-images.githubusercontent.com/47037905/142773781-8e660caa-d363-4084-8f85-30797ba46d1f.png)

Apps:
Nextcloud 22.2.3
Gestion 1.2.0

**Comment by baimard** [comment]
is it when you navigate fastly ?

**Comment by Valdnet** [comment]
> is it when you navigate fastly ?

Yes 😉.

**Comment by baimard** [comment]
Known bug :) thank you

**Comment by Valdnet** [comment]
Turns out the issue has been resolved.

**Comment by Valdnet** [comment]
I am reopening the issue.

During the first launch of the application, when the database is still empty, the following error appears:

![obraz](https://user-images.githubusercontent.com/47037905/154019639-6776746e-fc0d-42ca-a4c6-65051c1d468e.png)

And there is an endless loading of quantities in the menu:

![obraz](https://user-images.githubusercontent.com/47037905/154020025-f0e8045c-86c2-4b43-adfe-7eb43816956a.png)

Apps:
Nextcloud 23.0.1
Gestion 2.0.4

**Comment by baimard** [comment]
Can't reproduce ...

**Comment by Valdnet** [comment]
This happens when the tables in the database are not created during installation or have been deleted.
