### ISSUE TITLE
[EN] Apps: add product bug

### ISSUE THREAD

**Issue by baimard** [baimard/gestion#58]
Apps:
Nextcloud 22.2.3
Gestion 1.2.0
PHP 8.0

Creating a Product under "Product"  using "Add Product" this error appears:

**"Error: Too few arguments to function OCA\Gestion\Db\Bdd::insertProduit(), 1 passed in /var/www/nextcloud/apps/gestion/lib/Controller/PageController.php on line 241 and exactly 3 expected"**

with the pop-up [object Object]
No product can be added

_Originally posted by @Norbert-D in https://github.com/baimard/gestion/issues/55#issuecomment-979483524_

**Comment by baimard** [comment]
In version 1.2.0 error in Bdd.php : 

```
107	    public function insertProduit($idNextcloud,$ref,$des){
108	        $sql = "INSERT INTO `".$this->tableprefix."produit` (`id`,`id_nextcloud`,`reference`,`description`,`prix_unitaire`) VALUES (NULL, ?,?,?, 0);";
109	        return $this-> execSQL($sql, array($idNextcloud,$this->l->t('Reference'),$this->l->t('Designation')));
110	    }
```

must be replaced by : 
```
    public function insertProduit($idNextcloud){
        $sql = "INSERT INTO `".$this->tableprefix."produit` (`id_nextcloud`,`reference`,`description`,`prix_unitaire`) VALUES (?,?,?,0);";
        $this->execSQLNoData($sql, array($idNextcloud,$this->l->t('Reference'),$this->l->t('Designation')));
        return true;
    }
```

Correction in 1.2.2

**Comment by baimard** [comment]
Please confirme that version 1.2.2 correct your bug.

**Comment by Norbert-D** [comment]
I can confirm that in the version 1.2.2  the Bug is fixed
Merci for this fast support

**Comment by baimard** [comment]
I try to do my best, I know thatcan be an important app for small company :)
