### ISSUE TITLE
[EN] Quote does not save in NC Error in comment

### ISSUE THREAD

**Issue by Norbert-D** [baimard/gestion#59]
Gestion V 1.2.2
NC         V 22.0.3
PHP       V 8.0

When trying to save a quote to the NC I get an error 
"Error: An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'comment' at row 1
POST /index.php/apps/gestion/update"

The comment only has to words "billed quaterly"
I also deleted the comment and checked the DB same error

Question:
The Quote Number is a longtext and comment 255 is this correct on the DB

Detail log:
`"app":"index","method":"POST","url":"/index.php/apps/gestion/update","message":"An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'comment' at row 1","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0","version":"22.2.3.0","exception":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'comment' at row 1","Code":1406,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1780,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1719,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Statement.php","line":193,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/PreparedStatement.php","line":87,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":245,"function":"execute","class":"OC\\DB\\PreparedStatement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":141,"function":"execSQLNoData","class":"OCA\\Gestion\\Db\\Bdd","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Controller/PageController.php","line":264,"function":"gestion_update","class":"OCA\\Gestion\\Db\\Bdd","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"update","class":"OCA\\Gestion\\Controller\\PageController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","Line":114,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'comment' at row 1","Code":1406,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":94,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Statement.php","line":189,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/PreparedStatement.php","line":87,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":245,"function":"execute","class":"OC\\DB\\PreparedStatement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":141,"function":"execSQLNoData","class":"OCA\\Gestion\\Db\\Bdd","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Controller/PageController.php","line":264,"function":"gestion_update","class":"OCA\\Gestion\\Db\\Bdd","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"update","class":"OCA\\Gestion\\Controller\\PageController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'comment' at row 1","Code":"22001","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":92,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Statement.php","line":189,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/PreparedStatement.php","line":87,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":245,"function":"execute","class":"OC\\DB\\PreparedStatement","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Db/Bdd.php","line":141,"function":"execSQLNoData","class":"OCA\\Gestion\\Db\\Bdd","type":"->"},{"file":"/var/www/nextcloud/apps/gestion/lib/Controller/PageController.php","line":264,"function":"gestion_update","class":"OCA\\Gestion\\Db\\Bdd","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"update","class":"OCA\\Gestion\\Controller\\PageController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":92}},"CustomMessage":"--"},"id":"61a0e6e1864a6"}`

**Comment by baimard** [comment]
Dear Norbert-D,

sorry for that, is it possible to have a screen of the structure of the table : *NC*_gestion_devis where *NC* is your prefix.

**Comment by Norbert-D** [comment]
`

Column | Type | Comment
-- | -- | --
int(11) Auto Increment |  
date |  
longtext |  
int(11) |  
varchar(64) |  
varchar(255) [comment] |  
varchar(64) [1.0] |  
varchar(255) [New] |  

`
As well one record
`

Modify | id | date | num | id_client | id_nextcloud | comment | version | mentions
-- | -- | -- | -- | -- | -- | -- | -- | --
edit | 1 | 2021-06-01 | CA21000011-1 | 1 | norbert.demps | billed quaterly | 1 | Accepted
`
![image](https://user-images.githubusercontent.com/63411134/143604773-bb885364-becb-4a1e-8477-2d934cbde15c.png)

**Comment by baimard** [comment]
what is your SGBD ? PGSql or Mysql or ?

**Comment by Norbert-D** [comment]
It is  a MySQL 
MySQL version: 5.5.5-10.5.5-MariaDB-1:10.5.5+maria~focal t

no spaces checked the DB and each field as well at client and product.
Tested a new one with out touching comment still same error.

![image](https://user-images.githubusercontent.com/63411134/143609981-5bf8de3d-9335-45a8-b445-43e6880c3d62.png)

**Comment by baimard** [comment]
it's possible to join me on a private instant conversation ? Discord, Whatsapp, messenger, send me by mail contact@cybercorp.fr :)

**Comment by baimard** [comment]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>413 Request Entity Too Large</title>
</head><body>
<h1>Request Entity Too Large</h1>
The requested resource does not allow request data with POST requests, or the amount of data provided in
the request exceeds the capacity limit.
</body></html>

**Comment by Norbert-D** [comment]
The problem is in ModSecurity of the Appache2 config
quick fix 
`	<LocationMatch /index.php/apps/gestion/savePDF>
	<IfModule mod_security2.c>
	SecRuleEngine Off
	</IfModule>
	</LocationMatch>`

But need to look deeper into the server settings for that as the PHP settings are correct Nginx is fine only reports the ModSecurity error.

Thanks

**Comment by Norbert-D** [comment]
From my side issue could be closed
Thanks again and regards from Canada

**Comment by baimard** [comment]
Thank you too for your collaboration :)
