### ISSUE TITLE
[EN]  Font and translation when choosing a currency

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#60]
When choosing a currency, the font display should be improved and the possibility of text string translation added.

![obraz](https://user-images.githubusercontent.com/47037905/143607152-b428bb08-d3cd-4678-8a59-cad7d4af4823.png)

App:
Gestion 1.2.2

**Comment by baimard** [comment]
> of text string translation added.

Translation are in transifex.

>When choosing a currency, the font display should be improved 
don't understand that

**Comment by Valdnet** [comment]
The font encoding needs to be corrected:

![obraz](https://user-images.githubusercontent.com/47037905/143609230-1865eaef-eadc-4434-a8d5-ef364c5041ae.png)

![obraz](https://user-images.githubusercontent.com/47037905/143609552-45f0eac4-4ac8-4168-9700-859f27f2969b.png)

![obraz](https://user-images.githubusercontent.com/47037905/143609444-3cf8eb0e-6a0b-4c7f-a9b4-201a2375f324.png)

Currency name [text strings](https://github.com/baimard/gestion/blob/57005a5ebe6b32377adc53208276152acb98b379/src/js/modules/currency.mjs) are not present in Transifex.

**Comment by Valdnet** [comment]
@baimard There were additional errors in currency names:

![obraz](https://user-images.githubusercontent.com/47037905/153609030-74e15772-3a6f-4ed1-9c86-21517a5c6ace.png)

![obraz](https://user-images.githubusercontent.com/47037905/153609193-e8d9cb47-bed1-4460-841a-936c6123a960.png)
