### ISSUE TITLE
[EN] Means of payment

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#64]
I propose to add a selection of predefined means of payment so that when issuing an invoice, it is possible to quickly select a payment method:

![obraz](https://user-images.githubusercontent.com/47037905/143614539-9310bc8e-f5b5-4b01-894d-a78ec7f534f0.png)

**Comment by baimard** [comment]
No free text. thanks

**Comment by baimard** [comment]
but in futur I'm gone add datalist with all value write by the user in other quote or bill

**Comment by Norbert-D** [comment]
I must say I like this little app and the discussions great job!

For this feature I have a few suggestion as well.
- would be good to be able to add the payments method details to the footer of the invoice for example bank details here it would be good to be able to format it for better use of the client.
- The list would be good to be editable via settings for example add interact E-Transfer
- check box if paid to quickly edit it

**Comment by baimard** [comment]
Please transfert this issues to the discussion section,

https://github.com/baimard/gestion/discussions/categories/ideas
