### ISSUE TITLE
[EN] Choosing "Date of service"

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#65]
I propose to add a selection of the date of the service from the calendar:

![obraz](https://user-images.githubusercontent.com/47037905/143614666-8f45f659-0543-4254-b82f-9a9fc647c927.png)

**Comment by baimard** [comment]
No free text required by others users

**Comment by Valdnet** [comment]
Free text makes the application less user-friendly. The user has to manually enter the service date every time.

**Comment by baimard** [comment]
but service can be only for a mouth or for multiple day. Need free text
