### ISSUE TITLE
[EN] Change "Stats" to "Status"

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#66]
I suggest changing the names "Stats" to "Status" for "Invoices" and "Quote" and choosing by defined status names.

- Invoices

![obraz](https://user-images.githubusercontent.com/47037905/143615862-1cf48545-88f6-4aa6-a2a0-624919f32ba2.png)

- Quote

![obraz](https://user-images.githubusercontent.com/47037905/143616455-50e24356-0011-4c1a-8a8a-b3a41a2fa2e5.png)

**Comment by baimard** [comment]
> choosing by defined status names

Definitely no, because I want to let people free

**Comment by Valdnet** [comment]
Users can be given freedom by configuring actions in separate application settings.
It is pointless to keep typing the same similar actions to issue an invoice or a quote. This is laborious and inconvenient for the user. Plus, it's easy to make a mistake or make a typo.

Configuration of permanent actions by the user in an additional configuration, and then only its selection through the menu from the selection window facilitates the use of the application, speeds up work and excludes spelling mistakes.
These are just my observations. The choice is yours, but we all want the app to grow and be user-friendly. This is the only way to achieve full success.

**Comment by baimard** [comment]
You can open a conversation in https://github.com/baimard/gestion/discussions
