### ISSUE TITLE
[EN] Items "Actions"

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#67]
At a lower screen resolution, the "Action" elements for "Quote" and "Invoice" overlap.

- Quote:
- 
![obraz](https://user-images.githubusercontent.com/47037905/143690368-f67e5ed8-d5a8-4ff1-b68b-1e5e2316d8ed.png)

- Invoice:

![obraz](https://user-images.githubusercontent.com/47037905/143690341-de1565ce-d4e4-4a8c-b249-51372faa402c.png)

App:
Gestion 1.2.2

**Comment by baimard** [comment]
Solved in 1.3.1 (Next release)
