### ISSUE TITLE
[EN] Long data loading

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#68]
In my opinion it is too long to load data to the proportion of data in the database:

![obraz](https://user-images.githubusercontent.com/47037905/143690652-1fd0a710-1d05-4748-9f29-9e93d3560ecb.png)

If you switch to another application while loading data, you get an error:

![obraz](https://user-images.githubusercontent.com/47037905/143690610-bb2a264b-7d79-40a8-bf71-1564bb606d30.png)

App:
Gestion 1.2.2

**Comment by baimard** [comment]
You have to speak with nextcloud team because I'm depending of nextcloud framework.

**Comment by Valdnet** [comment]
There are various applications running in the NC and their operation is not slow. I understand, if you have a large amount of data in the database, the reading process is so long, but with one client and two products, the data should load very quickly.
