### ISSUE TITLE
[EN] Search

### ISSUE THREAD

**Issue by Valdnet** [baimard/gestion#69]
The test string "Search" must be placed in the dialog box:

![obraz](https://user-images.githubusercontent.com/47037905/143690692-7be22e74-8a05-4122-865a-bba60dc21952.png)

After change:

![obraz](https://user-images.githubusercontent.com/47037905/143690796-aa79fa4c-7c56-4506-9452-bee135a374e2.png)

App:
Gestion 1.2.2

**Comment by baimard** [comment]
I can't adapt the application for every person.

**Comment by Valdnet** [comment]
> I can't adapt the application with every person desir.

But it's not about customizing the app for a single user (for me). There is a trend that you can no longer describe it next to the search window, it's a waste of space and it looks a bit strange now.

See for yourself what it is like in the App Store Nextcloud:

![obraz](https://user-images.githubusercontent.com/47037905/143765964-de33a1e0-d413-416a-8a1d-e9a91bba4479.png)

I just mean the good of the application 😉.
