### ISSUE TITLE
[EN] Company name with accents creates PDF that will not open in Files

### ISSUE THREAD

**Issue by RavanH** [baimard/gestion#84]
When a company name with special characters, like é for example, is used, and the invoice or quote is saved to Files as a PDF, then that filename will prevent the PDF from being opened in the PDF viewer...

**Comment by baimard** [comment]
Taken into account

⁣cordialement,
Benjamin AIMARD​

Le 4 janv. 2022 à 19:05, à 19:05, Rolf Allard van Hagen ***@***.***> a écrit:

**Comment by RavanH** [comment]
Hi Benjamin, I also noticed that if the Client first name and surname are left to their default (Prénom et Nom dans mon cas) the PDF is not saved to Files at all. But I guess this is a minor issue because one would not normally leave those fields to their default...

**Comment by baimard** [comment]
Just need precision : 
- Special characters are in the name of the PDF or in content of the PDF ?
If there are in the content of the PDF I will suspect a bug in nextcloud : https://github.com/nextcloud/files_pdfviewer/issues/381#issuecomment-845806364

for the other bug, you're right and I'm going to correct it in next release. Thank you very much !

**Comment by RavanH** [comment]
A company name like "Médiris" will create a PDF filename like "DEVIS_M&eacute;diris_2022001_v0.1.pdf" which does not open in the File PDF viewer. After changing the filename manually (replacing the &eacute; with an é) will solve that problem.

**Comment by KaiBuskirk** [comment]
Gestion- pdf workflows are critical.. will be placing much work on this app it's very nice!
